### ISSUE TITLE
[3.0][feature] unit tests (PHPUnit)

### ISSUE THREAD

**Issue by jkufner** [panique/huge#172]
Hello,
there are no tests. Most of the important code should be covered by tests, so you will know when someone breaks something.

I recomend PHPT tool to do that (http://qa.php.net/write-test.php). It is simple and very versatile. You create directory with one file per test. Each file contains script, its description, and expected output. PHPT then executes and evaluates results.

PHPT is used by PHP itself.

Example of one simple test (one file):

    --TEST--
    Hello world test
    --FILE--
    <?php
    echo "Hello World\n";
    ?>
    --EXPECT--
    Hello World

Command to execute this test: `pear run-tests`

    Running 1 tests
    PASS Hello world test[hello-world.phpt]
    TOTAL TIME: 00:00
    1 PASSED TESTS
    0 SKIPPED TESTS

This test tool is also useful when writing new code. You simply let it generate nice output and when you are done, you copy generated output to `--EXPECT--` section.

**Comment by panique** [comment]
v3.1 (in develop branch) has now first unit tests :)
