### ISSUE TITLE
[3.x][potential feature] allow being logged in (parallel) from multiple devices

### ISSUE THREAD

**Issue by devplanete** [panique/huge#282]
Hello panique,

We have a problem with remember-me cookie on version 2-advanced and 4-full mvc.

If we use only one PC with one browser, no problem.... but if we use different PC or different browsers on the same PC, the remember-me token don't work.

Normal because each time we login the first time (with form) on a new browser, we reset user_rememberme_token  ! And all cookies containg the previous user_rememberme_token are now not valid anymore.

We will have to store multiple user_rememberme_token for the same user in the database.
I thinks it's the only way to allow user to logoff in one PC without impact on the other PC.

Have you another idea?

**Comment by JFJanssen** [comment]
Dear all,

I would be very interested in being able to configure wether or not to allow parallel logins:
A - Never (setting as a default, site-wide)
B - Always (setting as a default, site-wide)

In addition to A or B, I'd like tho option to allow overrides to the site-wide settings. Such overrides, if allowed by the site admin, would ideally be stored per user.

What do others think? Is it desireable to switch between allowing and disallowing site-wide parallel logins? And what about per-suer exceptions to these rules?

**Comment by panique** [comment]
He, I'll close this ticket as this is now handled via https://github.com/panique/huge/issues/724
