### ISSUE TITLE
[INTERESTING] login without password (using smartphone QRs)

### ISSUE THREAD

**Issue by panique** [panique/huge#290]
Gentlemen,

one of my favourite (german) PHP blogs just posted a very very interesting solution for SECURE login-processes while using a (possibly infected, keylogged etc.) computer in internet cafes, hotels, universities etc. You know what I mean.

This is awesome! According to the article this/something similar has been tested by Google, too.

(german) article:
http://www.phpgangsta.de/sesam-oeffne-dich-sicher-einloggen-im-internetcafe

Github repo:
https://github.com/PHPGangsta/Sesame

Demo:
http://sesame.phpgangsta.de/

Feel free to experiment with this and maybe pushing this feature into the 2-advanced / 4-full version.

**Comment by panique** [comment]
Hey, I'm currently  "cleaning" the project a little bit and moving feature-requests like this to an own list inside the readme file (find it under the "future features" point). I hope you are okay with it, as  most tickets here are new features and not really bugs or so.

My idea is just to avoid this project from getting oversized by too many features, so I'm closing the ticket, but for sure linking it from the readme in case somebody wants to implement this.

I hope you are all okay with this. :)

**Comment by 10vish** [comment]
hai, i wanted to change the url to custom url, can you please help
