### ISSUE TITLE
Wrong Captcha on Registration

### ISSUE THREAD

**Issue by chalupagrande** [panique/huge#319]
Every time I try and register a new user, it says I have the wrong Captcha, despite being certain it is correct. 

I did a var_dump of these variables (when the Captcha was HC34) in the class/registration.php file: 

var_dump($_POST["captcha"],$_SESSION['captcha'],strtolower($captcha), strtolower($_SESSION['captcha']));

and got the following:

string(4) "HC34" NULL string(4) "hc34" string(0) ""

I can't figure out how to fix it.

**Comment by vijendermaan** [comment]
Hi 
i want to my open text and page link for show the message after click on submit button..
where i can add a page link or text after click on submit button .

please help

**Comment by panique** [comment]
??? Hey, if you have a question then please open a ticket! you have just written a completely unrelated question below a closed ticket that's 1.5 years old and has nothing to do with your question.
