### ISSUE TITLE
 [RuntimeException] vendor does not exist and could not be created. 

### ISSUE THREAD

**Issue by ghost** [panique/huge#392]
When I do `composer install`  I get `[RuntimeException] vendor does not exist and could not be created.` I am doing this in `/var/www/`. I haven't modified the `composer.json` file either.

**Comment by borislemke** [comment]
Should anyone be stumbling upon this thread in the future, I fixed the issue by disable xdebug.
sudo php5dismod xdebug
sudo service restart {server} restart
replace {server} with nginx / apache2 depending on which server you are running

**Comment by fmaaref** [comment]
just execute sudo composer install

**Comment by Sharabaddin** [comment]
**sudo** composer install

**Comment by dleone81** [comment]
works well typing
sudo php composer.phar install

**Comment by ygordutra** [comment]
sudo composer.phar install

**Comment by vegas0250** [comment]
If you using a webhook us a deploy tool, you have to execute "composer install" with access rights of the web user. In my case it was "apache:apache".

So i did something like that:
1. cd project_folder/
2. sudo chown -R apache:apache vendor/
3. sudo -u apache composer install
4. that's it

**Comment by jackeratarina** [comment]
$which composer
/path/to/composer
$sudo /path/to/composer install
this could work

**Comment by vacar** [comment]
**Just another case, if you use docker-compose:**

**Problem:** _Read-Only Mount Binding_

**Example:** (docker-compose.yaml)
   ```
     php-fpm:
          volumes:
              - ./app:/usr/share/nginx/html/:ro,cached
```
If its **ro**, you cannot write to that directory within the container because its read-only. Just change the **ro** part to **rw** to fix this.

- ro = read-only
- rw = read-write

**Comment by sulimov** [comment]
> In general, please use the support forum for questions like that. This has something to do with your (broken?) composer installation, not with php-login. Your folder (var/www) probably is read-only or has not enough rights. for a quick fix, try `chmod -R 777 /var/www`, but dont use 777 in production!


But it is interesting that thanks to this question, some people, like me now, visited this GIT))

**Comment by Alexisgt01** [comment]
`chown -R www-data:www-data .`
`usermod -a -G www-data yourlinuxusername`
`find . -type d -exec chmod 755 {} \;`
`find . -type f -exec chmod 644 {} \;`
`sudo -u www-data composer install`

**Comment by Slisarenko** [comment]
If you're using docker:

**Comment by mfrosch** [comment]
Got the same problem.
On my system the folder already existed, but with different lower/upper cases. "vendorFolder" -> "vendorfolder"
Deleting it and run composer again solved the issue.
