### ISSUE TITLE
Nginx support  - Add Rewrites rules

### ISSUE THREAD

**Issue by svenkatreddy** [panique/huge#407]
Can someone please add instructions to support for nginx server?

I personally used this project on apache and later i tried to move to nginx. i'm facing issues with rewrite rules.

Why nginx? 
Apache has serious configuration  issues especially for low memory boxes
nginx is super fast

Amount of work?
I'm not expert on nginx but i'm definitely sure, it is just couple of correct rewrite rules to make it work.

**Comment by jumong** [comment]
How  do it with Nginx?

**Comment by panique** [comment]
@all: Please dont post into this ticket, as it's extrmeely old! I really dont know how people land here, maybe via Google ?

Have a look here for the current nginx-ticket, also with a sexy solution:
https://github.com/panique/huge/issues/622

xoxo
