### ISSUE TITLE
login/loginWithCookie  and more general calls to header("location:$url")

### ISSUE THREAD

**Issue by atdotslashdot** [panique/huge#409]
I'm getting web  redirect loops when trying to use rememberme and  having a hard time figuring out how to debug it....
is the logic in Controller.php constructor correct?

 // user has remember-me-cookie ? then try to login with cookie ("remember me" feature)
        if (!isset($_SESSION['user_logged_in']) && isset($_COOKIE['rememberme'])) {
            header('location: ' . URL . 'login/loginWithCookie');
        }

Wont this cause a redirect loop if the URL is already . URL . 'login/loginWithCookie' ?

should it be something like
    $url = filter_var($_SERVER['REQUEST_URI'], FILTER_SANITIZE_URL);
    if($url!=='/login/loginWithCookie')
        {  
            header('location: ' . URL . 'login/loginWithCookie');
            exit;
        }

Also, should we have a call to  exit after all the calls to header('location: '...) to prevent further code from  running?

**Comment by scriptdevelop** [comment]
I have the same error please let me know info about this?
If(!isset.......
loginWithCookie doesn't redirect well.....and go loop of redirect and return 302 HTTP response
Thanks a lot ..
