### ISSUE TITLE
[3.x][suggestion] CSRF Token

### ISSUE THREAD

**Issue by GrahamCampbell** [panique/huge#416]
Would it be a good idea to start sending CSRF tokens with all form data, and validating it at the other end?

**Comment by panique** [comment]
@GrahamCampbell @TemaSM @thierryve @atdotslashdot This feature is now implemented (develop and master branch), currently only used (by intention) on the login and the username changing form.

If you are interested in the code, please have a look here: https://github.com/panique/huge/pull/693
done by @OmarElGabry. This looks and works really fine and I think it's an really well written and still easy-to-use implementation.
