### ISSUE TITLE
[3.0] LIMIT 1 on some SQL Queries

### ISSUE THREAD

**Issue by CaptainKarma** [panique/huge#445]
Hi guys,

I've been building from the Advanced script and noticed that you aren't using LIMIT 1 on any of your queries.  I had a look at the latest MVC and you aren't using LIMIT 1 there either.

Is there any reason?  I appreciate that performance isn't probably a major issue for a login script however it seems best practice.  

Example login-model.php
       // check if new username already exists
        $query = $this->db->prepare("SELECT user_id FROM users WHERE user_name = :user_name");
        $query->execute(array(':user_name' => $user_name));
        $count =  $query->rowCount();
        if ($count == 1) {
            $_SESSION["feedback_negative"][] = FEEDBACK_USERNAME_ALREADY_TAKEN;
            return false;
        }

Using LIMIT 1 would make it stop as soon as it found a hit rather than continue to search the whole table?

I think you could also tweak it slightly and save the variable;

$query->execute(array(':user_name' => $user_name));
if($query->rowCount() > 0) {   // If data exists
 $_SESSION["feedback_negative"][] = FEEDBACK_USERNAME_ALREADY_TAKEN;
 return false;
}

(Seems Using LIMIT 1 when searching on the Primary Key seems to be waste of time)

Thought I would raise it for discussion :)

Cheers

Further Info;
http://stackoverflow.com/questions/5924115/using-limit-1-in-mysql

http://stackoverflow.com/questions/1774361/is-limit-1-recommended-for-query-where-where-condition-is-based-on-pk

http://www.databasejournal.com/features/mysql/article.php/3918631/Top-10-MySQL-Best-Practices.htm

LIMIT 1 When Getting a Unique Row
There are some queries that are meant to only return one row, such as those which fetch a unique record, or that verify whether or not there are any records that satisfy the WHERE clause. In such cases, adding LIMIT 1 to your query can increase performance. This reduces execution time because the database engine will stop scanning for records after it finds the first matching record, instead of going through the whole table or index.

**Comment by atdotslashdot** [comment]
Is it easy to generate a link here to the push in develop branch  (or is it easy to find this specific change in devlop branch on another page?) Thanks

**Comment by atdotslashdot** [comment]
found it...
https://github.com/panique/php-login/commits/develop?page=2
https://github.com/panique/php-login/commit/9379e4efb676b76864d72ab31a2a771deaec37c4

**Comment by panique** [comment]
Usually it's automatically linked here
