### ISSUE TITLE
[4.0] Let's introduce logging

### ISSUE THREAD

**Issue by sopitz** [panique/huge#487]
Is there a reason why there is currently no logging available? If you want I can introduce that fpr 3.0. Just let me know.

**Comment by panique** [comment]
The new version will be 3.0, not 2.1 (as the changes are too big), so let's move this to 4.0!

**Comment by panique** [comment]
Or, if somebody has a proper solution for 3.0: Send you commits :)

**Comment by tankerkiller125** [comment]
Been working on my logging solution. So far its not complete and its in a heavily modified version of this project (Almost everything that I can get from a DB comes from a DB including the config) However it shouldn't be too hard to redo the logging and implement it into the original.

**Comment by JFJanssen** [comment]
At least a basic structure for logging, including a working example (like the CRUD-example for Notes) would be quite welcome; I think most users can create -a- version of logging, but this framework is so nice and clean that including a working vversion of this would benefit many users, I'm sure.

**Comment by panique** [comment]
Hey, I'm currently  "cleaning" the project a little bit and moving feature-requests like this to an own list inside the readme file (find it under the "future features" point). I hope you are okay with it, as  most tickets here are new features and not really bugs or so.

My idea is just to avoid this project from getting oversized by too many features, so I'm closing the ticket, but for sure linking it from the readme in case somebody wants to implement this.

I hope you are all okay with this. :)
