### ISSUE TITLE
[4.0] What about making it RESTful?

### ISSUE THREAD

**Issue by sopitz** [panique/huge#488]
I think this project is a pretty damn good way to secure an application. And it easily works out of the box with only ONE disadvantage: You can only use it in PHP projects.

One of the major benefits of a PHP project in my eyes is the ease of getting up and running. Why dont we use this advantage and port that script to another version. Let's have an restfull api that you can use in ANY project, regardless of platform or technology, which is still super easy to set up and get running.

What do you think? Bullshit idea or something worth to be discussed?

**Comment by panique** [comment]
The new version will be 3.0, not 2.1 (as the changes are too big), so let's move this to 4.0!

**Comment by tankerkiller125** [comment]
For an API I've been working on I made a temp solution by editing the Auth class and making a single view that converts arrays to json. Then for all my views I just add the little variable system with the Model I need to call and then in the Model I just have the functions return arrays. Granted its a very dirty trick and I don't plan to use it this way for too long. And if I ever want to render out some HTML I can still do it like I normally would (although I can't use Authentication on them)

**Comment by abmmhasan** [comment]
https://github.com/educoder/pest
https://github.com/jmathai/epiphany
https://github.com/evantahler/PHP-DAVE-API

First one is better though!

**Comment by panique** [comment]
Hey, I'm currently  "cleaning" the project a little bit and moving feature-requests like this to an own list inside the readme file (find it under the "future features" point). I hope you are okay with it, as  most tickets here are new features and not really bugs or so.

My idea is just to avoid this project from getting oversized by too many features, so I'm closing the ticket, but for sure linking it from the readme in case somebody wants to implement this.

I hope you are all okay with this. :)
