### ISSUE TITLE
[4.0] What about supporting modules?

### ISSUE THREAD

**Issue by sopitz** [panique/huge#498]
I know, this project is only about the login but as we discuss more and more options even for the login type: What do you think of implementing a small platform that allows you to easily add modules and therefore change the behavior of the script? (e.g. adding a 2-factor-auth module, no-password-but-token-module, qr-code-module, ...)

It could be done via composer but that would make the implementation effort a lot higher because this would be considered usable in all kinds of projects. (Or am I missing something?)

I would expect something like: I unzip one module into "application/modules/<xyz>" and only configure the module the way I need it to be and thats it.

What do you think? Is that too big for this project? Which risks do YOU see? Any general thoughts?

**Comment by panique** [comment]
The new version will be 3.0, not 2.1 (as the changes are too big), so let's move this to 4.0!

**Comment by panique** [comment]
Hey, I'm currently  "cleaning" the project a little bit and moving feature-requests like this to an own list inside the readme file (find it under the "future features" point). I hope you are okay with it, as  most tickets here are new features and not really bugs or so.

My idea is just to avoid this project from getting oversized by too many features, so I'm closing the ticket, but for sure linking it from the readme in case somebody wants to implement this.

In this case I think the most simple solution would be to work with composer, this might be much simper than implementing middleware inside this little framework..

I hope you are all okay with this. :)
