### ISSUE TITLE
[DOCUMENTATION] What is the best way to provide documentation and support for this project?

### ISSUE THREAD

**Issue by sopitz** [panique/huge#504]
Hi everyone,
do you have good services that php-login could use to provide meaningful docs and maybe some Q&A forum to support this project?

My suggestion would be something like readme.io (http://php-login.readme.io/v1.0/docs). What tools did you find useful so far?

**Comment by panique** [comment]
Hey everybody, as I slowly moving this project to its End of Life it might be the best option to write a short docu directly into the readme file and a longer documentation diretly to GitHub's wiki pages of this project. HUGE is quite simple so, this will do :)
