### ISSUE TITLE
[4.0] total rewrite on top of a REAL (micro) framework (Slim, Laravel, ...) ?

### ISSUE THREAD

**Issue by panique** [panique/huge#523]
Hey Ladies & Gentlemen,

I'm the main author behind php-login and want to discuss the future of the project with you in this ticket. Feel free to comment and speak freely, let's brainstorm this.

### A. The future of php-login

The user authentication ("login") feature of php-login is obviously useful for lots of people, but the underlaying application structure is just a self-made quick-solution. In 2015 php-login will be rewritten, and to avoid creating another (pseudo) PHP framework the big question is: Should this project ...

1. ... be rewritten on top of a well-written, widely accepted and future-proof framework ? I'm thinking of [Laravel](https://github.com/laravel/laravel) here.
PRO: high-quality code/architecture possible
CON: this will raise the barrier for developers who are not on the "real framework" skill level. Hmm, but then [php-login-minimal](https://github.com/panique/php-login-minimal) might be an alternative...

2. ... be rewritten with a *extremely reduced architecture* under the hood, self-written (?) or by using a micro-framework like [Slim](https://github.com/codeguy/Slim). Slim is more a router than a real framework as it comes without an own application structure, so I'm also unsure here. But in general this option feels good.

3. ... be rewritten as a plugin etc. for every custom framework. I've no idea how this could be possible, but maybe it's an option.

4. ... other ideas ?

### B. How do authentication libs in big frameworks look like in 2014/2015 ?

Maybe the user auth / login solutions for major frameworks have evolved so much that php-login is completely obsolete now (I've written php-login because there was no easy-to-use and easy-to-understand standalone user auth solution available in 2012, beside that basically all auth tutorials were using horrible md5 hashing etc.). Please let's discuss this a little bit.

**Comment by panique** [comment]
Current status 25th January 2015: 

- 2.0 will be archived as the "old-stable", latest snapshot of 2.x is the v2.1.1 release.
- 3.0 will be the new version, release if in the next days. New architecture, massive rewrite, everything is as native as possible (so 3.0 is NOT using a micro framework under the hood). The project is also renamed to HUGE (to avoid the too generic name "php-login". the big PHP guys usually don't like it when a project name is too generic, and I basically agree with that)
- 4.0 might be a potential new version, rebuilding the status of 3.x on top of Slim, Silex or so, allowing quite professional things like RESTful architecture, Middleware, etc.

Let's release 3.0 for now and then let's introduce new features, step by step, into 3.x, over the entire year. I think this is a good plan :)

**Comment by tankerkiller125** [comment]
I will say it now that as a user that has never used a real framework the whole reason I even use php-login/HUGE was for the MVC framework. Even when I don't need authentication or logins I use HUGE because of its amazing ease of use and simple interface.

**Comment by Domeman** [comment]
Can this be used with a Firebird SQL database?
Any interest in Firebird SQL Database?

**Comment by panique** [comment]
@Domeman 
1. your questions has absolutly nothing to do with this ticket.
2. this is also totally out of scope of the project, as it has absolutly nothing to do with the login process.

please dont post stuff like that here.

**Comment by Domeman** [comment]
Whatever donkey

**Comment by normai** [comment]
On 2015-02-09 16:11, Roger wrote:
> Can this be used with a Firebird SQL database?
> Any interest in Firebird SQL Database?

See https://github.com/normai/php-login-xdb/issues/2

**Comment by panique** [comment]
Hi, I'm closing this ticket, the reason is: Most other frameworks also have proper login systems, so there's no need to rewrite this on top of Laravel or so, this wouldn't make sense. I think it's cool to keep this project as tiny and independet as it is.
