### ISSUE TITLE
[POSSIBLE FEATURE] OAuth2 implementation

### ISSUE THREAD

**Issue by panique** [panique/huge#528]
Upcoming versions of php-login / HUGE will get OAuth2 support for sure. This ticket here is for collecting information, ideas etc. regarding this feature.

**Interesting libs:**
https://github.com/thephpleague/oauth2-client
https://github.com/artdarek/oauth-4-laravel

The Facebook OAuth2 part has been copied to a standalone script btw:
https://github.com/thephpleague/oauth2-facebook

**Comment by panique** [comment]
Excellent lib https://github.com/artdarek/oauth-4-laravel

**Comment by M0ritzWeide** [comment]
Oh Yeeeah oAuth <3

**Comment by tankerkiller125** [comment]
Although I like the libs your looking at it makes it rather complex for someone to add a custom provider.  (Or at least based on my experimenting of the first lib)

**Comment by panique** [comment]
@tankerkiller125 These libs are the most common standards in the PHP world (as they come directly from the PSR-makers / phpleague). Feel free to post alternatives.

**Comment by tankerkiller125** [comment]
Unfortunately it seems that the lib I used to use is no longer with in the standards. Fair enough I'm sure that we can learn how to add providers.

**Comment by tankerkiller125** [comment]
Also just another suggestion to the Oauth portion is that mabey we could implement a PHP server into it as well as the client (so that people wanting to make their site an Oauth provider can do so)

**Comment by abmmhasan** [comment]
one thing, Google is leaving OAuth 2.0. Which does you can't use OAuth library with Google anymore (effective from April 20-21). I have tried to told it in another post earlier but before I describe further the issue closed.

**Comment by panique** [comment]
@abmmhasan Thanks, good to know!

**Comment by Dominic28** [comment]
Here it says OAuth2 is deprecated but you can still use it: https://developers.google.com/identity/sign-in/auth-migration#timetable

Only OpenID2 will shut down april 20.

**Comment by tankerkiller125** [comment]
And it's only the early versions of oauth2 through are deprecated. The
newer (final) versions are fully supported

**Comment by abmmhasan** [comment]
@Dominic28 and @tankerkiller125 , if you have read the contents in that link <a href="https://developers.google.com/identity/sign-in/auth-migration">Migrating to Google Sign-in</a> carefully you will see they will not support it but just a backward compatibility for existing users after April 20. They have already told to migrate to "Google Sign-in". Check it!

**Comment by panique** [comment]
As this is too much work and I also want to slowly put this project to End Of Life it might be okay to close this ticket and just link it from the readme (maybe somebody want to fork this project and really implement OAuth2).

**Comment by bbowesbo** [comment]
Did anyone manage to implement OAuth with this ?

**Comment by NightFury19910101** [comment]
Yes, I can implement OAuth2
发件人: Brad<mailto:notifications@github.com>
发送时间: Thursday, August 22, 2019 6:13 PM
收件人: panique/huge<mailto:huge@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [panique/huge] [POSSIBLE FEATURE] OAuth2 implementation (#528)


Did anyone manage to implement OAuth with this ?

―

**Comment by bbowesbo** [comment]
Have or Can?

**Comment by NightFury19910101** [comment]
I can

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
