### ISSUE TITLE
[3.2][fix] Return proper 404 for missing favicon.ico, missing images etc.

### ISSUE THREAD

**Issue by neon5** [panique/huge#530]
I set a breakpoint in libs\Application.php in __construct() and found it was getting hit twice.

The second hit is a get of favicon.ico and it was not found so it looks like there is a behind-the-scenes redirect to the error page happening.  However, there is no visual effect on the rendered page view.

This seems like extra and unnecessary work going on.

What I did was under this line: 

if ($this->url_controller) {

I added this:

if ($this->url_controller == 'favicon.ico') {
    return;
}

I don't know if that's the best way but it seems to be working for me.

**Comment by panique** [comment]
I think this could / should be fixed within the .htaccess, as the browser tries to call a static file, so this could be catched outside of the php application.

**Comment by panique** [comment]
The project now has a favicon and also a nice "empty-image"-fall in the HTML header.
