### ISSUE TITLE
verification email not working after registration in my xampp localhost environment with smtp4dev

### ISSUE THREAD

**Issue by amitgeek** [panique/huge#544]
I have followed this tutorial(http://www.dev-metal.com/install-php-login-windows-7-8/ ) 
and everything is working fine but verification  email is not working

I am using smtp4dev and i am also attaching screenshot of php.ini file

![untitled](https://cloud.githubusercontent.com/assets/4692473/5585345/596753a6-90ce-11e4-88bd-572b3eb1c694.png)

after submitting register form it shows that email sent  but then NOTHING HAPPENS!

This message should be shown as per tutorial

![smtp4dev-php-login-mail1](https://cloud.githubusercontent.com/assets/4692473/5585321/e1a0f732-90cd-11e4-9a43-2bc9b7717a76.png)

**Comment by mmuzammil45** [comment]
Hy amitgeek!
Have you found solution for this problem ?
