### ISSUE TITLE
[REFACTORING] LoginController only for login flow

### ISSUE THREAD

**Issue by slaveek** [panique/huge#549]
Hi.
Looking through changes in LoginController I began to think about some methods in it.
My impression is that some of the methods like:

showProfile, editUsername, uploadAvatar, changeAccountType
(all which need authentication) 

are not quite related to login process.

This methods are created to do user actions **after** login process (edit, upload, show etc.) and don't have nothing to do with correct, safe login. 

IMHO it's worth to consider in future to separate this methods in eg. UserController.
This can:
* keep LoginController to do login / logout process and make it very tiny
* let user to do all actions in UserController. It's also good place to put more user actions later.
* bring more logic in url's:
  * user/editusername instead of login/editusername
  * user/uploadavatar instead of login/uploadavatar
  * user/changeaccounttype instead of login/changeaccounttype

It can be a bit cleaner I think.

Just idea.
Take care.

**Comment by panique** [comment]
Hey slaveek, a very very good point! Thanks, I'll do this in the next days.
I have a very good feeling on the new version, things are going into a beautiful direction here!

Have a wonderful evening/day/morning :)

**Comment by M0ritzWeide** [comment]
Oh Yeah this is a nice Idea :D :+1:

**Comment by Dominic28** [comment]
Yes sounds great! I did this with the user profiles on a project, too.

**Comment by panique** [comment]
Done! This is just a first preview, everything might change for sure!

**Comment by panique** [comment]
in develop branch btw

**Comment by slaveek** [comment]
Hi Chris
I see that this issue is marked as done and closed but no changes in LoginController. Is not that a bit small mistake ;) ?  I think that the idea here was to clean LoginController (look at the issue title).
Maybe that's because of LoginModel changes.

BTW LoginModel looks so good now. The model directory is very clear and easy to navigate. It's extremely easy to find function that you need.

Shouldn't LoginController and controller dir look similar to model?

**Comment by panique** [comment]
@slaveek Ah damn, you're right! I've indeed just cleaned the model, not the controller. Okay, ticket is open again. :)

Changes will come around beginning of FEbruary.

**Comment by panique** [comment]
Okay, the changes will take a liiiittle bit longer :)

**Comment by panique** [comment]
Thanks to everybody, this is now done by slaveek's commit via https://github.com/panique/huge/pull/747
