### ISSUE TITLE
[3.0] announce documentation / write short quick-start-documentation

### ISSUE THREAD

**Issue by panique** [panique/huge#579]
As there's currently absolutly no documentation (beside the in-code comments) a quick-start-tutorial / quick documentation would be cool.

A real documentation should also come up later.

**Comment by cybernet** [comment]
I suggest the wiki

**Comment by panique** [comment]
@cybernet Me too, but there has been a wiki since 2012 and NOBODY finds it :) Wikis on GitHub seems to be a dead-area. I would suggest a quick-start in the readme-file itself (which is autoamtically shown here on github) and then a real documentation on an independent server or service, there are some nice tools out there to write good docs!

Let's use the best tools available, and also have a look on how other projects do this. TherE's also another ticket already discussing this: https://github.com/panique/huge/issues/504
