### ISSUE TITLE
[3.2][new feature] little native language system (internationalization, i18n)

### ISSUE THREAD

**Issue by Dominic28** [panique/huge#582]
Hey,
As you made it possible to load text with Text::get(), I created a very simple language system with it. I let the user choose the language while registering and save it to the database. Then I'm just checking which file needs to be loaded in the text class.

Additionally I'm reading out $_SERVER['HTTP_ACCEPT_LANGUAGE'] to show unregistered users the site in their prioritized language (if available).

Are you interested in this simple solution? Because you said it's not really needed some time ago.
I can't create a pull-request now as my version of huge is too different, that's why I'm asking.

**Comment by panique** [comment]
Hi Dominic, in generell it's a good feature, but I think it might be better to keep the focus on the login system and don't integrate any features that are related to the login process!

In the old php-login process there was a internationalization feature but this made things much more complicated.

Maybe, if it's extremely easy and a fully independet class: Can you show a little bit of code ?

Thanks & have a nice day

**Comment by Dominic28** [comment]
Basically it's just this part. You can see I moved the text-file from the config folder to a language folder and created folders for each language (like app/lang/en).

![unbenannt](https://cloud.githubusercontent.com/assets/2126807/5976612/3dc73ad8-a890-11e4-82ed-6d49f7af5f63.PNG)

**Comment by panique** [comment]
I love the simplicity of your code! Good stuff, this should definitly go into the project! Let's discuss this a little bit, maybe there are pros / cons and other have different opinions.

**My suggestions:**
1. maybe move the internationalization-part to an own method, so it can be used / not used with one line of code. Also good for potential upcoming unit tests.
2. the definition of the language (= WHERE and HOW will be defined which language the user sees) should be discussed

Good feature! Thanks for coming up with this proposal!

**Comment by Dominic28** [comment]
Thanks! I even removed the switch, so the language-file is searched just by the content of the user_lang session (with strip_tags).

To detect the language I got this in the constructor of app/core/controller.php
```
if (empty(Session::get("user_lang"))) {
    if (isset($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
        // Save the first two letters to the session
        Session::set("user_lang", strtolower(trim(strip_tags(substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2)))));
    }
}
```

Parts of this are from stackoverflow. But I would need to search for a link.

**Comment by Dominic28** [comment]
I found a smaller problem with my solution. If you got multiple language files, you always need to get sure that each language file contains every text. Otherwise there will be an empty place on the site.

Example:
You got the following entry in the english language array: "MENU_LINK_HOME" => "Home" but you forgot to set it up in the other languages.

This could be solved by requirering the language array, check the array for the entry and load the standard language if it's empty.

**Comment by panique** [comment]
Hey, I've linked this feature from the project's readme in case somebody wants to implement this.

Hope if it's okay for you when i close this ticket.

**Comment by vizzielli** [comment]
I know this is old. I've made something like this and copy now some of your code.

About missing text:
"This could be solved by requirering the language array, check the array for the entry and load the standard language if it's empty."

I've something different for this:
```
if (file_exists('../application/lang/'.$lang.'/strings.php')) {
    self::$texts = require('../application/lang/'.$lang.'/strings.php');
} else {
    self::$texts = require('../application/lang/de/strings.php');
}
```

Become ->
```
self::$texts = require('../application/lang/de/strings.php');
if (file_exists('../application/lang/'.$lang.'/strings.php')) {
    self::$texts = require('../application/lang/'.$lang.'/strings.php');
}
```

So, you load main language and override only exist strings. But really don't know which is better, double request or a check for each string call?

Thanks for your code!

**Comment by Kayumba** [comment]
Hello, I use huge login for my application. I would like to use several languages(tongues) in the application. Somebody has a directory containing everything.
I also ask you for the translation of this in French

Return array ("FEEDBACK_UNKNOWN_ERROR" = > " Unknown error occurred! ", "FEEDBACK_DELETED" = > " Your account has been deleted. ", "FEEDBACK_ACCOUNT_SUSPENDED" = > " Account Suspended for ",
thank you

**Comment by mauro-balades** [comment]
> self::$texts = require('../application/lang/de/strings.php');
> if (file_exists('../application/lang/'.$lang.'/strings.php')) {
>     self::$texts = require('../application/lang/'.$lang.'/strings.php');
> }

Remember to check if texts exist!
```php
if (!self::$texts)
```
