### ISSUE TITLE
user is registered when verification email is sent

### ISSUE THREAD

**Issue by rprincejr** [panique/huge#589]
Im using the huge code. I have made no changes to the code. The site works fine except when a user registers. The user goes into the database, but when the verification email is sent the user is somehow verified without clicking the link in the email. Thus making the user_active field a 1 and the user_activation_hash field null.

If I comment out sending the email to test, everything goes into the database fine. Meaning user_active  is 0 and the user_activation_hash field is the hash thats generated.

Other than that, the script works fine. And again, Ive made no changes to the code. Ive exhausted all possibilities for a fix, but Im at a loss. 

So Im considering this a bug.

Lastly, great script. Keep up the good work.

**Comment by rprincejr** [comment]
This issue is closed. The issue ended up being an issue with my a2 hosting account.

**Comment by panique** [comment]
Can you go into detail what exactly the problem was ? Maybe it affects others people too and it worth a notice in the (upcoming) documentation.

**Comment by rprincejr** [comment]
Hey Chris. Sure, I can go into detail. Ive beat my head against a wall for
4 days over one issue. I originally starting using php-login to teach
myself MVC. I understand programming and have developed sites for 10 years.
But I decided to learn a new framework. Enough of my background.

The problem I have is with the registration system. When a user registers,
the database inserts a new user with user_active = 0 and the activation
hash = the hash generated. So far so good. Then the next step is to send a
verification email to the users email so they can verify and activate the
account. Thats where the problem starts. When the email sends, somehow the
link in the email is executing. Because the link will verify the account,
that is what is happens.

If I comment out sending the email, then everything is the way its suppose
to look in the database. ie. user_active = 0 and activation_hash = the
generated hash.

But when the email sends, and I check the database user_active = 1 and
activation_hash = null.

I thought maybe a2 had an email scanner that was causing links in emails to
be executed when the email leaves the server. They are currently looking
into the situation.

To further troubleshoot, I downloaded and installed the huge project to one
of my sub domains. I left the code untouched. Same problem. When the email
goes out, it verifies the user.

Then I installed the huge project to my godaddy account. Again I left the
code untouched. It works fine. No issues.

So that tells me there something set incorrectly at a2. Since it works fine
at godaddy. When the godaddy test succeeded, I closed the issue at github
since its no fault of the code.

At the moment, it still isnt resolved at a2. I dont want to move hosting
but if they cant find the problem and fix it I have no other choice. Its a
shame, because a2 has been a good host so far.

Ronnie

On Mon, Feb 2, 2015 at 4:13 PM, Chris <notifications@github.com> wrote:

> Can you go into detail what exactly the problem was ? Maybe it affects
> others people too and it worth a notice in the (upcoming) documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/panique/huge/issues/589#issuecomment-72538971>.
>



-- 
Ronnie Prince
812-583-6205

**Comment by panique** [comment]
Uh! That's interesting, and I've heard this issue before ! This is indeed a problem, but totally out of scope of the code itself, as it's clearly a spam-crawler is something.

How exactly do you handle your mails ? I've only seen real SMTP over external services (companies that send emails for you so you can rely 99% that these mails really end up at the users's inboxes) in action, no idea how others handle this...

**Comment by rprincejr** [comment]
For this code, I tried both. First I tried send mail. Then I setup SMTP and
tried it. The end result was the same. Have you had any issues a2? Im
looking at Arvixe as an alternative.

On Mon, Feb 2, 2015 at 5:36 PM, Chris <notifications@github.com> wrote:

> Uh! That's interesting, and I've heard this issue before ! This is indeed
> a problem, but totally out of scope of the code itself, as it's clearly a
> spam-crawler is something.
>
> How exactly do you handle your mails ? I've only seen real SMTP over
> external services (companies that send emails for you so you can rely 99%
> that these mails really end up at the users's inboxes) in action, no idea
> how others handle this...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/panique/huge/issues/589#issuecomment-72553391>.
>



-- 
Ronnie Prince
812-583-6205

**Comment by panique** [comment]
@rprincejr How exactly are you using smtp ? A2 is just server hosting and has nothing to do with mail sending afaik.

**Comment by rprincejr** [comment]
I think it was just a miscommunication. I was talking about using sendmail
and smtp in the huge code project.  Sendmail is the native php mail
function and SMTP uses the phpmailer class.

On Mon, Feb 2, 2015 at 6:17 PM, Chris <notifications@github.com> wrote:

> @rprincejr <https://github.com/rprincejr> How exactly are you using smtp
> ? A2 is just server hosting and has nothing to do with mail sending afaik.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/panique/huge/issues/589#issuecomment-72559797>.
>



-- 
Ronnie Prince
812-583-6205
