### ISSUE TITLE
Universal Authentication module!

### ISSUE THREAD

**Issue by abmmhasan** [panique/huge#591]
Why not you try <a href="https://github.com/hybridauth/hybridauth">hybridauth</a> module?

**Comment by panique** [comment]
@abmmhasan Can you please form a real question ? No idea what exactly you want to say.

**Comment by tankerkiller125** [comment]
@panique I think he's saying that the hybridauth module would be good for Oauth2 instead of using each individual services oauth2 lib

**Comment by panique** [comment]
@all: Like explained several times in the according tickets: 3.x will become a OAuth2 implementation with the package listed in the ticket. Please inform yourself before you write useless tickets.

**Comment by abmmhasan** [comment]
Well, I should have responded to this long ago! Bu was not much active online!

As far I know GOOGLE will stop OAuth 2.0 support on their app system. It might be effective from April or May.
