### ISSUE TITLE
TOTP Authentication Services?

### ISSUE THREAD

**Issue by tankerkiller125** [panique/huge#595]
Would it be possible to maybe implement TOTP/OTP into the authentication system using a library such as https://github.com/ChristianRiesen/otp I think that it might offer some more authentication and because of the way that specific library works it would allow for DUO and Google Authenticator to be used without the website owner having to pay fees.

I would make a fork however I am not very good at implementing new things into existing projects.

**Comment by panique** [comment]
He, i think that's too special for the project. Do people really use these things ? Let's keep it simple.

Other opinions on this ? Maybe somebody has more experience.

**Comment by tankerkiller125** [comment]
I honestly do use these things as it adds a tiny bit of extra security that I like. However I do see your point and would also like other oppinions

**Comment by oisian1** [comment]
I don't feel like this feature is necessary. Yes it related to the login process. However it's also quite a specialised need to have this, and would not be utilized in the majority of projects
