### ISSUE TITLE
Styling issue when refreshing page with f5

### ISSUE THREAD

**Issue by oisian1** [panique/huge#597]
Noticed this little style/browser issue  today

http://imgur.com/Rpbl2Dt
This is a fresh install of Huge.
On the left is Chrome and on the right is IE, whilst viewing the notes page and pressing f5 the my accounts button drops down slightly, not sure why this happens just pointing it out, it did not do this in IE and i have not tested Fire fox or any other browsers

**Comment by panique** [comment]
Can you reproduce this on the live demo in any way ? looks fine here.

**Comment by oisian1** [comment]
Hi, I just fresh installed it on my machine at work, fired up chrome,  headed to /note/index  Pressed F5 and Boom http://i.imgur.com/gXVI9em.png

**Comment by panique** [comment]
I've checked this on 50+ browsers, including lots of chrome versions on every OS, and it looks perfect everywhere. Are you sure oyu have not zoomed the page or so ?

**Comment by oisian1** [comment]
Yeah positive that's not me, i have tried over two separate machines in two locations, on a 1080p screen and a 4k monitor at 100% and that's the result, it does only happen in chrome though, i have too tested in other browsers and it doesn't do it just chrome.

**Comment by panique** [comment]
Are you using an extremely long username, or a username that has very weird stuff inside ? Are you using a special localized browser version, like russiian or arabian or so ?

Can you look at the rendered frontend code why this is happening ?

**Comment by oisian1** [comment]
User name Oisian1, i am using the normal version of chrome no localization or anything, i have had a look through to rendered code and as silly as it sounds nothing changes between the My accounts dropdown being in the correct place and it not being in the correct place, i feel like this is a chrome bug, but i'm really not sure what's going on. .

**Comment by panique** [comment]
Is the OS Windows 7 ?

**Comment by oisian1** [comment]
yeah 64bit

**Comment by panique** [comment]
Can you please try to 
- login with a different username ?
- change the avatar ?
- maybe switch from gravatar to local avatar etc ?

There's outcommented code around this area (in view/_templates/header), maybe it's causing this.

**Comment by oisian1** [comment]
just a side note, it doesn't always do it on the first one or 2 F5's some times it won't change untill i have pressed it a few times, other times it does it on the first press of F5

**Comment by panique** [comment]
Any news on that ? Can you please try out the 3 things from my earlier comment, maybe it'S something from that list...

**Comment by oisian1** [comment]
No sorry, not had time been really busy this week, although im almost positive it's a chrome bug 
https://code.google.com/p/chromium/issues/detail?id=246875

**Comment by panique** [comment]
Hey, I'll close this for a while as it's not reproduceable and probably a frontend bug (if even). Feel free to reopen this ticket if you have more information on it (or anybody else can reproduce).
