### ISSUE TITLE
[feature] Shipping with Bootstrap 

### ISSUE THREAD

**Issue by oisian1** [panique/huge#598]
Although this is not technically a feature, i feel like if Huge was built with Bootstrap it would allow developers using this framework but who do not have a lot of experience with front end development kick start there projects at lot faster and easier. just a thought.

**Comment by panique** [comment]
He, this has been discussed several times before, and the result was mostly: This is a PHP login script, so let's focus on the PHP and login part and throw out everytihng that has nothing to do with this!

Let's keep it minimal as possible!

**Comment by Raoul9** [comment]
Hi,

Sorry for replying to closed ticket, but would you consider this with the help of the community? If you were willing to ship with the very basics of Bootstrap I think this would have some massive advantages for this project. I know the argument that let's focus on the PHP is indeed true, but in my opinion there has to be CSS regardless so why not use an existing framework that's hugely popular? In a sense we'd be outsourcing the CSS/HTML work... If anything using Bootstrap would make it more "minimal" as there would be less work involved.

Thanks

**Comment by panique** [comment]
Hmm, this is a php project, not a frontend project! No framework in the world ships with bootstrap or similar afaik, but correct me if I'm wrong here.
