### ISSUE TITLE
[question] Is it possible to upgrade from 2.x to 3.x ?

### ISSUE THREAD

**Issue by angryrancor** [panique/huge#605]
Been working a lot with the 2.0 release before 3.0 was committed, and I was wondering if anyone has explored an upgrade path/script from 2.0 to 3.0?  If not, I might be interested in exploring how much work it would be (checking file diffs, trying to figure out a process that works in _most_ cases..)

Has anyone else explored this?  I realize it may end up being a lot of work just apart from installing the new files and doing a file diff, but am curious about how others approached it, and if they succeeded in the end in migrating to the new version.

Cheers and thanks for helping maintain a wonderful project!

**Comment by panique** [comment]
:) Sorry, but for sure you cannot upgrade. This is nearly impossible, as it's two different applications, every line has been touched.

There's also no need to upgrade if you are already using 2.x, if your application is running fine! The new code is mostly made to make the project cleaner and simpler, but the features are nearly the same.

My personal opinion: Trying to upgrade to 3.0 would be so much work and would probably create a lot of bugs compared to simply leave it as it is, so from business perspective there's no value in upgrading!

Hope you are doing well,
Thanks
