### ISSUE TITLE
[3.2][improvement] Improving 404 page

### ISSUE THREAD

**Issue by slaveek** [panique/huge#609]
Hi,
now when the page (controller or method) is not found, app redirecting user to error page.
It's working perfectly trough this line:
```php
header('location: ' . Config::get('URL') . 'error');
```
Everything looks good but dev tools showing 302 status which still means that is found and 404 for error controller.

![302](https://cloud.githubusercontent.com/assets/2339178/6197461/9413603a-b3dd-11e4-9c2c-29c92a9dad63.png)
AFAIK most of the pages generate 404 page without redirecting. For the quick test here on github open your dev tools -> network tab and then click on https://github.com/panique/hug or https://www.youtube.com/wat?v=Jj6yXxVc21Y for another test
Dev tool showing 404 for page that we are looking for and the address in browser is not changed which means that wasn't redirection.
Maybe it's worth to consider to change redirection with load error controller like:
```php
require Config::get('PATH_CONTROLLER') . 'ErrorController.php';
$this->controller = new ErrorController;
$this->controller->index();
```
instead of
```php
header('location: ' . Config::get('URL') . 'error');
```

This give a bit nicer 404's handling.
![404](https://cloud.githubusercontent.com/assets/2339178/6197639/e326a616-b3e0-11e4-8034-98ec8e5c5c98.png)

**Comment by panique** [comment]
Good one! I would like to add this: Maybe it makes sense to do this,

```php
// proper 404
header('HTTP/1.0 404 Not Found', true, 404);
// hard exit, to make sure the php application stops. might not be necessary if application flow ends too
exit();
```

**Comment by panique** [comment]
@slaveek How would a GOOD 404 page look like ? I mean, real 404 plus a real page for the browser end-user.

**Comment by slaveek** [comment]
Hi.
Behind the scene quite important is to send a proper HTTP response status for page that is not found. That's very important especially for search engines. We can be pretty sure that this page don't be indexed.

For the end-user?
Everyone know how annoying is nearly blank page with the big red "Page not found" or "Sorry. Nothing here" etc. When we click on dead or broken link we'll should see page that:
- look the same as the rest of the site
- contain some nice, friendly or even funny info what can be wrong
- provide the most relevant links or give an option to search within your website
- etc

Generally keep user engaged with our website, help find what they were looking for and help users go out from 404 page.

Don't let the user go back to Google!
;)

**Comment by panique** [comment]
Hey gentlemen, can you please have a look ? I've pushed something to develop branch, but I'm unsure if this is the correct thing:

https://github.com/panique/huge/commit/250d1f52aebe554d630329845e2020682e60d035

**Comment by slaveek** [comment]
IMO:
1. Keep
```php
header('HTTP/1.0 404 Not Found', true, 404);
```
in ErrorController.php. This will give possibility to use ErrorController in any other situations where 404 is needed (ErrorController with 404 will be ready to use).
2. Change
```php
header('HTTP/1.0 404 Not Found', true, 404);
```
to
```php
header($_SERVER['SERVER_PROTOCOL'].' 404 Not Found', true, 404);
```
although I'm not sure that's important if 404 is passed as third parameter. [Here](
http://stackoverflow.com/questions/2769371/404-header-http-1-0-or-1-1#7608563) is some explanation.

**Comment by panique** [comment]
Done in develop branch, please allow some time for testing
