### ISSUE TITLE
[code quality] Scrutinizer wrongly shows 100% code coverage. Why ?

### ISSUE THREAD

**Issue by panique** [panique/huge#611]
I've just introduced some very simple very first tests in the develop branch, and set up automated builds and automated tests via Travis:
https://travis-ci.org/panique/huge/jobs/50843085

The code analyzer Scrutinizer uses this data to show a code coverage badge, which is surprisingly at *100%*, which is for sure not true:
https://scrutinizer-ci.com/g/panique/huge/

Can somebody say why this is happening ? (I'm new to this :))

**Comment by darezik** [comment]
Its showing a sensible value now. Maybe it needed time to observe after you connected it to your project?

**Comment by panique** [comment]
@darezik Are you sure ? It still says 100% under the link above... Can you have a second look, maybe it really just a (cache?) problem on my side.

**Comment by darezik** [comment]
My bad, was looking at something else. Test coverage, if you meant that, is still 100% for the 4 classes you've written tests for. but when I ran code coverage on an individual one, it considered you had covered all the code.
![screen shot 2015-04-02 at 8 05 13 am](https://cloud.githubusercontent.com/assets/10482574/6956607/0d40715e-d90f-11e4-8739-6a10acbe8e39.png)
