### ISSUE TITLE
[3.2][feature] Dont redirect to Error-Page

### ISSUE THREAD

**Issue by emptynick** [panique/huge#612]
I dont know if there is any special background to just redirect the user to the error/index site, but for me it has been useful to keep the page xyz/index (which does not exist) and show the contents from the error-page instead.
So basically instead of Redirect::to('...'); load the ErrorController and call the index() function.
For me its useful because otherwise the console shows "Error 404 file not found (...error/index/)" everytime a file is missing instead of the correct URL.

**Comment by tankerkiller125** [comment]
I have the same issue and it is indeed very annoying. I forget how I did it but in one of the older versions of HUGE (was php-login) I was able to fix this issue. I do not remember what I did to fix it though.

**Comment by emptynick** [comment]
Basically in application/core/Application.php
Change line 60 with:
require Config::get('PATH_CONTROLLER') . 'ErrorController.php';
$this->controller = new ErrorController();

And line 63 with:
require Config::get('PATH_CONTROLLER') . 'ErrorController.php';
$this->controller = new ErrorController();
$this->controller->index();

**Comment by slaveek** [comment]
HI. Look here
https://github.com/panique/huge/issues/609

**Comment by oisian1** [comment]
Yeah, there are two tickets open here for pretty much exactly the same thing

**Comment by emptynick** [comment]
Sh**, same problem, same solution.
Didnt see this, thanks for pointing out!

**Comment by panique** [comment]
Hey gentlemen, can you please have a look ? I've pushed something to develop branch, but I'm unsure if this is the correct thing:

https://github.com/panique/huge/commit/250d1f52aebe554d630329845e2020682e60d035

**Comment by tankerkiller125** [comment]
Looks good to me I'll test it when I get the chance.

**Comment by abmmhasan** [comment]
Error list:
301 Moved Permanently, 302 Moved Temporarily, 400 Bad Request, 401 Authorization Required, 403 Forbidden, 404 Not Found, 405 Method Not Allowed, 408 Request Timed Out, 415 Unsupported Media Type, 500 Internal Server Error, 501 Not Implemented, 502 Bad Gateway, 503 Service Unavailable, 504 Gateway Timeout, 505 HTTP Version Not Supported.

.htaccess:
ErrorDocument 503 error/503.php
ErrorDocument 401 error/401.php
ErrorDocument 500 error/500.php
ErrorDocument 301 error/301.php
ErrorDocument 403 error/403.php
ErrorDocument 400 error/400.php
ErrorDocument 408 error/408.php
ErrorDocument 302 error/302.php
ErrorDocument 405 error/405.php
ErrorDocument 415 error/415.php
ErrorDocument 404 error/404.php
ErrorDocument 501 error/501.php
ErrorDocument 502 error/502.php
ErrorDocument 504 error/504.php
ErrorDocument 505 error/505.php

Note: Don't mind my list but was trying to give listings also along with another possible solution...

**Comment by tankerkiller125** [comment]
Think you can consider it fixed.
