### ISSUE TITLE
[IDEA] Yeoman generator ? 

### ISSUE THREAD

**Issue by mohamedpsx** [panique/huge#613]
@panique , big fan of your php-login i used it in many projects. and wow huge is even bigger and better so keep it up. 

I am a dev in a small company where i have to be the full stack dev, so i was doing a lot of front end dev using tools like grunt bower and yeoman and their cool generators for scaffolding. and i had this idea why not create a yeoman generator for php-login or even huge? 

i just wanted your opinion and if you want i will keep you updated when i get to it.

**Comment by panique** [comment]
Hey, thanks! :) This is a for sure just a PHP project, so the focus is clearly on the php code, and I think it's a good idea to keep everything away from the project that is not pure PHP.

To be honest, i have no idea how yeoman works and i'm sure that 90% of the users also have no idea, so it would be more a problem that an helper.

As HUGE install without any frontend tools and totally works like that, it might be good to the future to keep it like that. Frontend devs will probablly be able to add their frontend tools within minutes by their own, and they will probably do it much better than us PHP devs would do :)

What do the others say ? Feel free to comment!

**Comment by tankerkiller125** [comment]
I'm not exactly sure how yeoman works either however I will say that a SASS/LESS compiler built in would kinda be nice and it would help with some front end based development.

**Comment by oisian1** [comment]
@tankerkiller125, there would be untold number of features that would be nice to have, but fall out of the scope of this PHP project. AS @panique said i feel like people with actually experience with these features and tools would be able to better integrate them for there own projects with less hassle. I agree with @panique on this one.

**Comment by tankerkiller125** [comment]
Very valid point
