### ISSUE TITLE
[bug] avatar image upload only handles .jpg correctly, not .png

### ISSUE THREAD

**Issue by dotemup** [panique/huge#614]
New install on godaddy cpanel. 
Using php 5.5 with gd.
Not using gravatar using local avatars.

When uploading png filetype as avatar the file gets upload as completely black.
jpg filetype uploads fine.

**Comment by Dominic28** [comment]
That's because currently every image is just saved as a .jpg file.
You can change this here if you want to change it quick: https://github.com/panique/huge/blob/develop/application/model/AvatarModel.php#L188

**Comment by panique** [comment]
Only .jpg is possible right now (however the code is a little bit broken here). I've removed .png completley inside develop branch.

Next release will hopefully have support for jpg and png again.

**Comment by panique** [comment]
Done, this is in develop branch now. The avatar upload feature can now handle jpg, png, gif.
