### ISSUE TITLE
[code quality] how to refactor these long if/else constructs ?

### ISSUE THREAD

**Issue by panique** [panique/huge#616]
Hey guys,

the [last "bad file" in the project](https://scrutinizer-ci.com/g/panique/huge/code-structure/develop/hot-spots) that has a C rating (all other have As or Bs) is this one here:

https://scrutinizer-ci.com/g/panique/huge/code-structure/develop/operation/%2Bglobal%5CRegistrationModel%3A%3AregistrationInputValidation

I'm very unsure how to refactor this (without making things more complicated), as it's simply a long if / else if / else if / ... / else list. Any recommendations ? After this refactoring the project will have a reating near 9.7 of 10 (!!). Naaaaice!

**Comment by slaveek** [comment]
Have you ever consider to skip ```else if``` condition end keep ```if``` only?
```php
public static function registrationInputValidation($captcha, $user_name, $user_password_new, $user_password_repeat, $user_email)
{
	// perform all necessary checks
	if (!CaptchaModel::checkCaptcha($captcha)) {
		Session::add('feedback_negative', Text::get('FEEDBACK_CAPTCHA_WRONG'));
	}
	if (empty($user_name)) {
		Session::add('feedback_negative', Text::get('FEEDBACK_USERNAME_FIELD_EMPTY'));
	}
	if (empty($user_password_new) OR empty($user_password_repeat)) {
		Session::add('feedback_negative', Text::get('FEEDBACK_PASSWORD_FIELD_EMPTY'));
	}
	if ($user_password_new !== $user_password_repeat) {
		Session::add('feedback_negative', Text::get('FEEDBACK_PASSWORD_REPEAT_WRONG'));
	}
	if (strlen($user_password_new) < 6) {
		Session::add('feedback_negative', Text::get('FEEDBACK_PASSWORD_TOO_SHORT'));
	}
	if (strlen($user_name) > 64 OR strlen($user_name) < 2) {
		Session::add('feedback_negative', Text::get('FEEDBACK_USERNAME_TOO_SHORT_OR_TOO_LONG'));
	}
	if (!preg_match('/^[a-zA-Z0-9]{2,64}$/', $user_name)) {
		Session::add('feedback_negative', Text::get('FEEDBACK_USERNAME_DOES_NOT_FIT_PATTERN'));
	}
	if (empty($user_email)) {
		Session::add('feedback_negative', Text::get('FEEDBACK_EMAIL_FIELD_EMPTY'));
	}
	if (strlen($user_email) > 254) {
		// @see http://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address
		Session::add('feedback_negative', Text::get('FEEDBACK_EMAIL_TOO_LONG'));
	}
	if (!filter_var($user_email, FILTER_VALIDATE_EMAIL)) {
		Session::add('feedback_negative', Text::get('FEEDBACK_EMAIL_DOES_NOT_FIT_PATTERN'));
	}

	// otherwise, return false
	return false;
}
```
This may increase rating, maybe.... I'm not sure. 
Also this has the additional advantage. It's display all errors during registration not just first occurred.
![screen shot 2015-02-21 at 19 19 52](https://cloud.githubusercontent.com/assets/2339178/6315616/3e6aff9e-b9ff-11e4-9b8c-e5c89e4123ba.png)
User can correct all errors straight away.

**Comment by Dominic28** [comment]
@slavekk It's returning all errors, because you moved the "return false" to the bottom where the "return true" should be in this case. I think you know that, too. In your case there's no way for the method to return true^^

**Comment by panique** [comment]
**Personal notice:** split this into 3 blocks:

- validateUserPassword
- validateUserName
- validateUserEmail

if all 3 are true, return true, else false

**Comment by panique** [comment]
My job is done here :)

![code quality](https://cloud.githubusercontent.com/assets/156321/6319540/bb9b4904-babf-11e4-97f8-f59923f202e6.PNG)

**Comment by Dominic28** [comment]
Good job :)
