### ISSUE TITLE
I can't login on Android.

### ISSUE THREAD

**Issue by ghost** [panique/huge#617]
Yes, bitches.

I am trying loggin in, but I can't do it.

I see, login form, again, and again. Bitch!

Not for idiots: I am using old version, and it's modificated. And maybe, don't updated.

**Comment by panique** [comment]
PHP is a server-side technology, so it has absolutly nothing to do with the user's operating system. People like you should not do development at all. You should not do ANY jobs at all, at least nothing involved with humans or animals.

Github's abuse team is on you. I hope you are proud of you, you seem to be a very intelligent person.

**Comment by SUCKmyDICKbitch** [comment]
Humans are animals, if you don't know this, you can fuck yourself.

I think, maybe this related a sessions...

Who know?

**Comment by panique** [comment]
Strong words for somebody who is obviously in a critical mental health state.
You are now blocked from writing here.

Please do everybody a favour and leave the internet, leave development and especially don't use this script anymore, you don't deserve it.

Ah yes, and it's weird that the most retarded people always think they are more clever than everybody else. The abuse team deals with people like you every day, so don't feel to safe in front of your computer.

And for everybody else: PERMABAN IS COMING and UK law enforcement is activly pulling trolls off the internet:
*Internet trolls face up to two years in jail under new laws*
http://www.bbc.com/news/uk-29678989

**Comment by oisian1** [comment]
+1 for @panique  Reply

**Comment by panique** [comment]
Closing due to trolling :)
