### ISSUE TITLE
[3.2][possible feature] Using a templating language for the view ?

### ISSUE THREAD

**Issue by M0ritzWeide** [panique/huge#621]
Hey,
i think a Templating Language like Blade would be very nice in this Framework.
It could give the View a lot more structure and clarity :)

**Comment by panique** [comment]
btw are you really 14 ? :)

side-note: current earworm: https://vimeo.com/120544816

**Comment by tankerkiller125** [comment]
Not exactly smart to ask for peoples age online... Even if this is a dev community (I'm much younger than I act) Just so that everyone can feel safe :) Other than that I like the idea of a tempting engine at the same time I hate it.

**Comment by panique** [comment]
@tankerkiller125 ??? I'm confused now! Moritz just said in another thread that he's 14 and I was just asking "for confirmation" (you know, maybe it was a typo or so). I think you are misreading this ... There was absolutly nothing negative in this.

Regarding the template engine: I think the focus should be on the login stuff, and everything else should be purely optional. Also, keeping on standard would be cool too. Maybe Twig ?

I prefer pure naked PHP btw :)

**Comment by tankerkiller125** [comment]
You are indeed correct I was reading it wrong. And I agree with you 100%
although a templating system would be nice it's a bit to much for this
framework.

**Comment by M0ritzWeide** [comment]
haha @panique yes im 14. But since the 09.March im 15.

**Comment by abmmhasan** [comment]
Please don't use any template engine! It's better as it is now as RAW!

**Comment by panique** [comment]
I would also prefer the simple-&-raw as possible approach.
But, how could a totally optional twig-view look like, has somebody maybe done this ?

**Comment by tankerkiller125** [comment]
@panique Haven't done this but I think it would be kinda cool to make it an optional thing.

**Comment by panique** [comment]
Okay I'm just closing this issue.
