### ISSUE TITLE
[3.x][feature] Redirect to last visited page after logging in (and not to default after-login-page)

### ISSUE THREAD

**Issue by jmlw** [panique/huge#627]
Hello, not sure if this has been asked before...

What would be the best way to redirect user to a controller that initiated an Auth::checkAuthentication()?

Scenario:
User opens home page (server/index)
User clicks link requiring login (server/profile)
Server redirects to login (server/login)
User authenticates and is redirected to home page (server/index)

Instead of returning user to the home page, how would one pass the data of the controller that required the Auth initially?

**Comment by panique** [comment]
Hi, exactly that is happening already!

Check Auth.php/checkAuthentication() and see `header('location: ' . Config::get('URL') . 'login');`

**Comment by jmlw** [comment]
Hi, I understand that the <code>header( 'location :' . $URL) </code> is already redirecting users.

What was was asking, hopefully phrased better, is that after user authenticates (when triggered by a <code>checkAuthentication()</code> call), the user be re-directed back to the controller where the <code>checkAuthentication()</code> call occurred.

An example:
- User is not logged in
- User goes to <code>website/note</code>
- Redirect to login
- User authenticates
- Return user to <code>website/note</code> since this is where the user tried to go but this location required authentication

I attempted to pass the calling URL as a POST variable, but ran into issues passing the variable from the <code>checkAuthentication()</code> function to the login page (I am not sure how to pass the variable during a redirect) as my PHP is quite rusty.

**Comment by panique** [comment]
Ah okay, now I get it :)

This would need to use cookies and save the last position of the user afaik. Any other opinions ? Feel free to submit this feature to develop branch if somebody has something.

**Comment by ldmusic** [comment]
Hi, a possible solution is to check on every request:
```
if (Session::get('currentPath')) {
    Session::set('lastPath',session::get('currentPath'));
    Session::set('currentPath',$_SERVER['REQUEST_URI']); 
} else {
    Session::set('currentPath',$_SERVER['REQUEST_URI']);
}
```
And now in the log in process check if there is a ```session::get('lastPath')``` and if true redirect to it after successful login.

**Comment by Dominic28** [comment]
@ldmusic Are you sure this would work right now? Auth::checkAuthentication is destroying the session before redirecting to login right now.

**Comment by ldmusic** [comment]
You're totally right! I had not looked into the code. Perhaps after destroy start a new session and add the path. But perhaps a cookie solution panique mentioned is better, or perhaps add something like 
```
'?ref='.base64_encode($_SERVER['REQUEST_URI'])
```
to /login. Only a few ideas. But make it secure ;)

**Comment by dvrcthewrld** [comment]
I frequently see this handled by merely passing the originating url as a GET variable that is passed along until login happens, at which point redirection takes its cue from the GET.  It doesn't make for the prettiest url, but it's only there for a moment, and it isn't the sort of url that anyone is likely to share anyhow.

**Comment by oisian** [comment]
http://stackoverflow.com/questions/14523468/redirecting-to-previous-page-after-login-php

Interesting read on the topic

**Comment by panique** [comment]
@all: Can somebody please have a second look on this new feature (https://github.com/tysonlist/huge/commit/715a73f69ef272ed5f2ae1c0394a96a02a5bff46) ? I'm unsure if this is the right way to go, maybe it has security issues.

But looks really good so far! Please allow some time for proper testing.

**Comment by tankerkiller125** [comment]
@panique Cookies is actually not a better option. Reason: MITM attacks can easily grab/edit cookies. Also most websites just handle this by putting the url to redirect to in a GET paramater. Then before redirection it verifiesthat the redirection is to its own domain. If it is then it continues the redirection to the requested page. If not then they redirect to there home page or show the user a warning with a button that allows them to choose between there homepage or the requested URL.
