### ISSUE TITLE
[code quality] Database table names

### ISSUE THREAD

**Issue by creadicted** [panique/huge#628]
Hey, please correct me when I am wrong. 
I thought that it was uncommon to use the table name again in its own rows. I know that it sounds really petty to change "note_text" just to "text" and "note_id" to "id" but in terms of code quality wouldn't it be appropriate? Or am I just pissing around? :)

**Comment by panique** [comment]
Hey, that's indeed a good question and afaik there's no proper convention on this. As far as I know it's always good to NOT write things more than once to reduce possible errors. But, in reality, joining tables can get super-messy when you have several columns with the same names from different tables, and giving each column a totally unique name is what has been used in several projects I have seen so far.

However, this is just my personal experience, maybe it's wrong. :)

What do the others say ?

**Comment by mohamedpsx** [comment]
@panique yes i agree with you, using table name in it's columns names is more clear and easy to understand and distinguish but it also can result in mysql conflict " ambiguous column name" in some simple join queries and will have to set aliases for the columns that you are selecting.

so in my opinion both methods have their pros and cons and it is up to the developer/team, but if any one got a better idea or a better convention to use it will be cool :D

**Comment by mohamedpsx** [comment]
JAVA devs tend to use the JPA convention and i don't know if that is something to inspire to or not since we are using php
