### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by AdamDenoon** [panique/huge#634]
I am getting a "The page isn't redirecting properly" error, and I think there's some kind of infinite loop caused by Rewrites. The htaccess files are untouched. I want this project installed only within a sub-folder on my server, which is pointed-to by a subdomain.

Here is my 000-default.conf:
```
NameVirtualHost *:80

<VirtualHost *:80>
	
	ServerAdmin webmaster@localhost
	<VirtualHost *:80>
           DocumentRoot "/var/www/html"
           <Directory "/var/www/html">
            AllowOverride All
             Require all granted
           </Directory>
     </VirtualHost>

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

<VirtualHost *:80>
    ServerName www.mysubfolder.myserver.com
    ServerAlias mysubfolder.myserver.com
    ServerAdmin admin@myserver.com
    DocumentRoot "/var/www/html/mysubfolder/public"
    <Directory /var/www/html/mysubfolder/public>
            AllowOverride All
            Allow from all
    </Directory>
</VirtualHost>
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

**Comment by panique** [comment]
He, I don't have much experience with server configs so I might be wrong here, but

```
    ServerName www.mysubfolder.myserver.com
    ServerAlias mysubfolder.myserver.com
```

looks super-broke. Don't do this and you should be fine.

**Comment by AdamDenoon** [comment]
That server config works correctly (the requests and responses land in the right place). It's just that when one lands in the /public folder, the htaccess instructions seem to loop. I commented out those lines and had the same problem. Even if I'm on localhost and directly attempt to access the index.php file, there's a re-direct and I get this error.

**Comment by tankerkiller125** [comment]
To be honest www. should never be appended to a subdomain and if you do it then you should just make it a CNAME of the mysubfolder.myserver.com or just redirect it to mysubfolder.myserver.com

(Coming from someone who's has run his fair share of sites)

**Comment by panique** [comment]
Yeah I totally agree: Don't make things more complicated than necessary, keep it as simple as possible ("but not simpler" :) ). In this case you're creating problems by setting up a super-weird edge-case that has absolutly no advantage, just a hell of downsides.

Even if you really really need this subdomain, then use it without www. ,as there's absolutly no advantage in doing so. If you still have problems, try to remove the www-stuff from the .htaccess file(s).

**Comment by AdamDenoon** [comment]
Thanks for the help, guys! I eliminated the nesting and the ".www" from the conf file and the issue was resolved. I have a new issue, however, so I will post that immeduately. Thanks, guys!
