### ISSUE TITLE
HUGE and simplicity

### ISSUE THREAD

**Issue by abmmhasan** [panique/huge#637]
Well, I love this project a lot. I love this for simplicity. Though I been working on older version of HUGE. Today I just downloaded the newest release.
& I got shocked.
Once I completed the installation (including composer installation), it becomes 5.96 MB in total.
Which does seems to me HUGE is slowly losing it's simple look, for what I loved it most.

**Comment by Dominic28** [comment]
Hey,
You can easily calm down if you take a look at what got this script so big.
It's php-unit in the vendor folder and this is just needed for unit tests.

**Comment by panique** [comment]
@abmmhasan The project is not 6 MB, just are just looking at the ENTIRE HISTORY that lays inside the hidden .git folder, including all the images from 2013 and 2014 I think.

HUGE is 420kb incl. everything when downloading, 180kb in the application folder, so i realy dont know what you mean.

The 2015'er HUGE is also much much smaller and simpler than the old php-login.
