### ISSUE TITLE
302 Found Error from jquery

### ISSUE THREAD

**Issue by jpveneracion** [panique/huge#641]
Hello! I am currently trying to build a website using HUGE (awesome script by the way.)

I am having problems including javascript files to load on views other than the default view.

Please see attached screenshots.
![index](https://cloud.githubusercontent.com/assets/4402293/7105232/6014b068-e141-11e4-8509-af79cb020b5e.png)

the metro.min.js loads correctly on the default view.

but when i go to the register view it gets a 302 found error...

![register](https://cloud.githubusercontent.com/assets/4402293/7105236/8ef0395c-e141-11e4-9d40-8ec0e969b00a.png)

I already even tried absolute url to file  but still wants to load the javascript from the register/js location...

Thanks for any tips you can give me. 

God bless! :)

**Comment by slaveek** [comment]
absolute url + clean cache
Maybe...

**Comment by panique** [comment]
He, try to load the .js files with a absolutle URL (like localhost/js/xxx.js), not with a relative URL (../js/xxx.js)... should do the job :)

**Comment by jpveneracion** [comment]
thanks! it's working now. i had to add the absolute url in load-metro.js :)

thanks and God Bless! :)
