### ISSUE TITLE
Rewriting URLs

### ISSUE THREAD

**Issue by mintpixels** [panique/huge#642]
Hey there!

I was curious about how I could cleanly re-write the URL structure of ID specific pages.

For instance: User logs in and is redirect to their home page - currently, "home/index/1"
Instead I would prefer the URL structure to be: "home?id=1" 

I would need to rewrite this structure in most places, so a global change would be appropriate. 

Thank you!

**Comment by panique** [comment]
@mintpixels He, you could post this (plus the used htaccess) on stackoverflow and I guarantee you, you'll have an answer within some hours :)
