### ISSUE TITLE
possible to run in a subdirectory?

### ISSUE THREAD

**Issue by jpveneracion** [panique/huge#648]
Good day again. i would like to ask if it is possible to run huge in a subdirectory of my website. 
here is what i want to do:
the main website will be a wordpress blog 
and i will build a custom application within huge in a subdirectory with seperate database from the wordpress blog.
i don't know if this is the proper venue to ask this but i asked anyway so sorry if it should not be asked here. :)

**Comment by panique** [comment]
Hey @jpveneracion , may I ask you why you wanna do this ? There's no reason to install two different projects on the same server, this will only bring you a lot of stress and problem and has absolutly no advantage. Servers are free or $5 these days.

To answer your question, yes, for sure it's possible to install in a subfolder, this is exactly what the autoinstaller does, have a look!
