### ISSUE TITLE
Appveyor always fails

### ISSUE THREAD

**Issue by tankerkiller125** [panique/huge#651]
Appveyor fails on any and all pull request. Mabey remove it from the project? Or include the project file that it wants. Almost all the current pull request would have passed if it weren't for Appveyor.

**Comment by panique** [comment]
@tankerkiller125 Definitly! I've never added it to the project and don't really know how to remove it :) There's no real reason to keep it (as this tests PHP on Windows Servers, which is extremely rare in the PHP world afaik)

**Comment by tankerkiller125** [comment]
The fastest way to get rid of it would to deny it access to your account
via you accounts applications page

**Comment by panique** [comment]
Done :)
