### ISSUE TITLE
Use without composer

### ISSUE THREAD

**Issue by kazyka** [panique/huge#652]
Is it possible to rewrite the code, so it works without installing it from composer?
I have learned a lot from the code, but seems like I miss alot of features, beacuse I haven't installed it with composer

**Comment by panique** [comment]
Hi Kazyka, in my opinion there is absolutely no logical reason why anybody would develop without composer. Composer is the standard in every PHP application and it's extremely easy to use, and it just gives advantages, no disadvantages. Using something without composer is much harder than doing it with it.

Also, there's a tutorial explaining everything and there's also an auto-installer, so you'll never have problems.

If you have never worked with composer, please take some minutes to jump into it, it's really cool and will lower your stress, work and problems so much :)
