### ISSUE TITLE
How to handle ajax requests ?

### ISSUE THREAD

**Issue by bribrink** [panique/huge#656]
How is everyone handling ajax calls? I'm going to build a pretty ajax-intensive project on top, want to prevent spaghetti...
Just curious...

**Comment by panique** [comment]
It's supereasy, simply use `renderWithoutHeaderAndFooter()` instead of `render()` in the controller. Or, if you want to put out JSON, like in most AJAX calls, do it with `renderJSON($normalArray)`. You can find this inside core/View.php and look how it works.

**Comment by bribrink** [comment]
Thank you! I'm new to this. I like the  simplicity;
