### ISSUE TITLE
RenderMulti causes errors in header

### ISSUE THREAD

**Issue by gduffy100** [panique/huge#659]
Hi Chris,

Great script and application structure, nice logical flow and easy to find things.

Just tried to implement renderMulti for a new view and it created an error in the header file where the active class if statements were looking for the variable $filename, which is now no longer defined. Wondering if you have an elegant solution to this issue in mind.

Maybe making $filename $filenames in all cases and always referencing $filename[0].

**Comment by gduffy100** [comment]
I added a line into the render multi function before the call to header as follows:

$filename = $filenames[0];

This resolves the issue because now $filename exists

**Comment by oisian** [comment]
$filename already exists, it's one of the parameters, if it doesn't exist then you have not set it

**Comment by panique** [comment]
Hey, this feature was build by an external author, so I cannot really say something. :(
But a big thanks for the fix, I'll put this into the project in the next days!

**Comment by gduffy100** [comment]
Hi oisian,
$filename is only instantiated in renderMulti after the call to header. Before that you only have the $filenames variable.
