### ISSUE TITLE
[TODO] more security for .htaccess

### ISSUE THREAD

**Issue by gujiman** [panique/huge#661]
hi, 

I was wondering, would it be wise to add a "please re-enter your password" when making changes to the username or email.

Take the following scenario:
1) user logs in and forgets to log out.
2) attacker then changes the users email to a new email.
3) attacker then sends a password reset to the new email.

Also i was just wondering why the user can not change the password when they are logged in?

**Comment by gujiman** [comment]
hi, sorry about this, i have a client who uses your script and wanted me to check it for security issues.

I ran Acunetix Vulnerability Scanner and it came up with no major issues, but made the following suggestions and solutions:

1) Clickjacking: X-Frame-Options header missing!
Vulnerability description
Clickjacking (User Interface redress attack, UI redress attack, UI redressing) is a malicious technique of tricking a Web user into clicking on something different from what the user perceives they are clicking on, thus potentially revealing confidential information or taking control of their computer while clicking on seemingly innocuous web pages. 

The server didn't return an X-Frame-Options header which means that this website could be at risk of a clickjacking attack. The X-Frame-Options HTTP response header can be used to indicate whether or not a browser should be allowed to render a page inside a frame or iframe. Sites can use this to avoid clickjacking attacks, by ensuring that their content is not embedded into other sites. 

How to fix this vulnerability
Configure your web server to include an X-Frame-Options header.
Add to .htaccess:

<IfModule mod_headers.c>
    Header always append X-Frame-Options SAMEORIGIN
</IfModule>

2) Cookie without HttpOnly flag set!
Vulnerability description
This cookie does not have the HTTPOnly flag set. When a cookie is set with the HTTPOnly flag, it instructs the browser that the cookie can only be accessed by the server and not by client-side scripts. This is an important security protection for session cookies.

How to fix this vulnerability
If possible, you should set the HTTPOnly flag for this cookie.
Add to .htaccess (don't use in your test site, it will not let you create cookies):

<IfModule php5_module>
   php_value session.cookie_httponly 1
   php_value session.use_only_cookies 1
</IfModule>

3) Cookie without Secure flag set!
Vulnerability description
This cookie does not have the Secure flag set. When a cookie is set with the Secure flag, it instructs the browser that the cookie can only be accessed over secure SSL channels. This is an important security protection for session cookies.

How to fix this vulnerability
If possible, you should set the Secure flag for this cookie.
Add to .htaccess (don't use in your test site, it will not let you create cookies):

<IfModule php5_module>
   php_value session.cookie_secure 1
</IfModule>

--------------

Other than the suggestions above i have to admit this is a very good and secure script you've made!

**Comment by panique** [comment]
Excellent! Thanks! I'll have a look and add this when there's time (currently I'm really packed with other stuff).

Regarding the re-entering of the password: Yeah, I remember that there was a discussion about this earlier in 2014, but I don't remember exactly why this feature was skipped. Maybe "because" most large sites on the web also don't ask for the password when changing email/username etc, but that's for sure not a very good reason :)

I'll create an extra ticket for this, maybe it will be in the next release 3.2.

Thanks!

**Comment by panique** [comment]
Hi, just a question regarding this: Adding `Header always append X-Frame-Options SAMEORIGIN` to the .htaccess always gives back a 500 internal server error in my tests, do you have an idea why ?

**Comment by panique** [comment]
2) is fixed by having this inside the config:

```
/**
 * Configuration for cookie security
 * Quote from PHP manual: Marks the cookie as accessible only through the HTTP protocol. This means that the cookie
 * won't be accessible by scripting languages, such as JavaScript. This setting can effectively help to reduce identity
 * theft through XSS attacks (although it is not supported by all browsers).
 *
 * @see php.net/manual/en/session.configuration.php#ini.session.cookie-httponly
 */
ini_set('session.cookie_httponly', 1);
```

**Comment by panique** [comment]
regarding 2) use_only_cookies is not necessary as this is activated / 1 by default since PHP 5.3:
php.net/manual/en/session.configuration.php#ini.session.use-only-cookies

**Comment by panique** [comment]
3) is also implemented, but optional as most people will not use SSL in their development environments. in the config you can find "'COOKIE_SECURE' => false,", which will be used when writing cookies. There's also a small documentation on this.

I think everybody who really needs security like this will find out easily how to use it, for everybody else the default setting is totally okay. As https is not standard and will break everything when used in a wrong way, it is better to make it optional. Just my 2 cents :)

**Comment by panique** [comment]
ah! :) http://stackoverflow.com/questions/20611893/can-somebody-please-help-me-to-avoid-internal-server-error-htaccess-apache2c

Hmm it might be better to make this optional as it might irritate users when activated by default (as it will generate server error 500 unless user has installed "rewrite headers" which is definitly not standard)

**Comment by panique** [comment]
Hey, regarding the 1) apache header stuff: I've added this including a if block (that asks if the apache rewrite headers module (?) is installed) into the .htaccess, commented out, so people can decide to use it if they really want to!

Thanks for the ticket, some good things have gone into the project now, I'll close it now!
