### ISSUE TITLE
Huge Version is missing Vendor and Libs folder

### ISSUE THREAD

**Issue by ajborn** [panique/huge#662]
I went to upgrade my version from 2.0(Advanced) to 3.0(Huge) and after setup I noticed the page erroring and it was due to the missing folders.  They are application/libs and vendor folders.  I checked my old version to make sure it came with that originally and I have the folders.

Is there a reason for the missing php files and folders from the project?

Or is this an actual mistake?

Please help I want to use the new version.

**Comment by panique** [comment]
Hey, you cannot upgrade from 2.0 to 3.0, these are two completely different architectures.
Also, the vendor folder comes from composer and has nothing to do with the project itself!

Have a look at the readme and you'll be fine :)

**Comment by ajborn** [comment]
Thanks for your response Chris.  I definitely did not read the tutorial close enough, thanks for the help, much appreciated.
