### ISSUE TITLE
[frontend bug in live demo] NoteController/index - Display error of user's note.

### ISSUE THREAD

**Issue by danoussh** [panique/huge#663]
Hello HUGE guys :)

I'm new to Github so I'm not sure if this is the right way of doing things but here we go.
I've just started using you Php Advance loggin script i'm going to change it with HUGE script.

On demo site of HUGE script, there is an error while displaying user's notes.
http://demo-huge.php-login.net/note/index

![Image of HUGE User's note display error](http://i58.tinypic.com/ei40gp.png)

You may notice that the information is offseted towards the left of the table and table headers. Meaning that column DELETE is empty.

Best regards,
Danoussh

**Comment by panique** [comment]
:) Thanks! Good eye for the details! I'll fix this in the next days.
Have a nice day
