### ISSUE TITLE
[STICKY][Optional feature] ReCaptcha Support

### ISSUE THREAD

**Issue by tankerkiller125** [panique/huge#665]
I fully understand that we don't want any more features for the project. I am simply creating this to give people a concept of how to add ReCaptcha to their own pages.

Composer command (official google lib)
`composer require google/recaptcha "~1.1"`

Code to add to any pages you want a captcha (will use built in if recaptcha not enabled)
```php
<?php if (Config::get('RECAPTCHA_ENABLED')) { ?>
<div class="g-recaptcha" data-sitekey="<?php echo Config::get('RECAPTCHA_SITEKEY'); ?>"></div>
<script src="https://www.google.com/recaptcha/api.js"></script>
<?php } else { ?>
<br><img id="captcha" src="<?php echo URL; ?>login/showCaptcha"/>
<br><input type="text" name="captcha" placeholder="Please enter above characters" required/>

<!-- quick & dirty captcha reloader -->
<a href="#" style="display: block; font-size: 11px; margin: 5px 0 15px 0; text-align: center" onclick="document.getElementById('captcha').src = '<?php echo URL; ?>login/showCaptcha?' + Math.random(); return false">Reload Captcha</a>
<?php } ?>
```

CaptchaModel Function (add anywhere you'd like)
```php
public static function checkRecaptcha($gReCaptchaResponse) {
    $recaptcha = new \ReCaptcha\ReCaptcha(Config::get('RECAPTCHA_SECRET'));
    $resp = $recaptcha->verify($gReCaptchaResponse, Request::server('REMOTE_ADDR'));
     if($resp->isSuccess()) {
        return true;
    } else {
        return false;
    }
}
```

Part you put into your function that checks for captcha (again compatible with built in captcha)
```php
if (Config::get('RECAPTCHA_ENABLED')) {
    if (!CaptchaModel::checkRecaptcha($captcha)) {
       Session::add('feedback_negative', Language::getText('captcha-wrong'));
       return false;
    }
} else {
   if (!CaptchaModel::checkCaptcha($captcha)) {
        Session::add('feedback_negative', Language::getText('captcha-wrong'));
        return false;
    }
}
```

And last but not least this will need to be added to the config array
```php
'RECAPTCHA_ENABLED' => true,
'RECAPTCHA_SECRET' => 'xxxxxxxxx',
'RECAPTCHA_SITEKEY' => 'xxxxxxxxxx',
```

**Comment by panique** [comment]
AWWESOMEEE !! Thank you so much, this should definitly go into the project by default! I'll do this in the next weeks when there's some time! :)

**Comment by tankerkiller125** [comment]
Your welcome. I might add that the `Language::getText` should be changed to the correct `Text::get` (I forgot to change it from my implemention)

**Comment by JFJanssen** [comment]
Thanks tankerkiller125!

Would indeed be great to see as a standard feature.

**Comment by mcanatalay** [comment]
Thank you tankerkiller125 there was a cpu issue in my server side. I think this would help me much.

**Comment by tankerkiller125** [comment]
@mcanatalay Not sure if it will help with CPU however it does reduce bandwidth (since verification and images come from google and not your server)

**Comment by mcanatalay** [comment]
Well, what does use cpu is image creating process and maybe key creating. Taking them externally surely help.

**Comment by panique** [comment]
FYI this script uses the most simple and native image creation possible in PHP, and rendering a captcha takes 1/1000sec on a standard CPU on a standard $5 server, so this should not be a big problem. @mcanatalay Can I ask you if you are using this in a very high-traffic scenario ?

**Comment by mcanatalay** [comment]
No. Simply pressing reload captcha gives me %10 of cpu level. It is only captcha related problem. First, I was tought it is about my "autoload.php" since I cannot use composer, but it is only happens when I press reload captcha.

**Comment by tankerkiller125** [comment]
Currently Refactoring this system (Hopefully bring the entire system into one well bundled system that doesn't require a bunch of extra code in the HTML)

**Comment by afermon** [comment]
Hi, I'm using the code above. However, I get the error "Fatal error: Call to undefined method Request::server()" that probably if because of Request::server('REMOTE_ADDR') in chechRecaptcha function. Does anyone knows how to get the client IP?  I'm not so experienced in php

**Comment by tankerkiller125** [comment]
Sorry about that I think I made the server function. Replace it with
$_SERVER['REMOTE_ADDR']

**Comment by mcanatalay** [comment]
Or you can add this function after cookie function in Request class.

```php
    /**
     * gets/returns the value of a specific key of the SERVER super-global
     * @param mixed $key key
     * @return mixed the key's value or nothing
     */
    public static function server($key){
        if (isset($_SERVER[$key])) {
            return $_SERVER[$key];
        }
    }
```

**Comment by lawkout2** [comment]
First off... I am a HUGE fan! I just tried to implement the reCaptcha and I get it to display and also get the green check mark but when submitting the form it always says the feedback error "The entered captcha security characters were wrong". I have added the $_SERVER['REMOTE_ADDR'] In the CaptchaModel.php and was wondering if there was anything else that needed to be updated.

**Comment by tankerkiller125** [comment]
The google lib should do most of the work. Make sure you have your keys
right?

**Comment by lawkout2** [comment]
Keys are correct. However I am a little confused on the google lib. I ran the -> composer require google/recaptcha "~1.1" but I cannot seem to locate the "recaptchalib.php". Forgive me as I am a little new to this.

**Comment by lawkout2** [comment]
Now realizing there is no recaptchalib.php with the new recaptcha. When comparing the built in captcha function to your recaptcha function:

**Comment by lawkout2** [comment]
Keys are correct. Everything seems to be correct. I am a little confused on the "CaptchaModel Function (add anywhere you'd like)" When comparing the physical path in vender/google/recaptcha ... it does not seem to look right. Below is the google recaptcha vedor directory structure. Can you tell me if its right.

![vendor](https://cloud.githubusercontent.com/assets/5105300/8991949/2353b534-36d2-11e5-8445-47a90d8c93dc.jpg)

**Comment by lawkout2** [comment]
Keys are correct. Since I am the only one commenting on this it must be something simple I am missing.

**Comment by videsignz** [comment]
Love the idea here...I keep getting an error when submiting
`Fatal error: Class 'ReCaptcha\ReCaptcha' not found in....`
I do not have a ReCaptchaController so not sure what do :/

**Comment by tankerkiller125** [comment]
@videsignz Please read the very fist post very clearly. The Controller is not built into the application and you will need to make it yourself. The code needed has been clearly laid out and should be simple to follow. So again please read the very first post in this issue.

**Comment by videsignz** [comment]
Yeah, I did everything else, then looked back and saw `composer require google/recaptcha "~1.1"`
What a dummy...

**Comment by tankerkiller125** [comment]
@videsignz I've done that a couple times :laughing:

**Comment by videsignz** [comment]
@tankerkiller125 Do you mind me asking something? I am not good with composer and have only used putty once to install HUGE. I have the option to directly install google/recaptcha by cloning the folder but not sure where in my directory it should go. I am assuming in the same base directory where HUGE is installed?

**Comment by videsignz** [comment]
Well, after everything is installed...I am receiving the error `missing-input-response` and that's it...keys are right...in the docs it is looking for `$_POST['g-recaptcha-response']` yet in the registration model it gets `Request::post('captcha')` so there needs to be another if statement here I think...I'll test it and post back here

**Comment by videsignz** [comment]
Ok, so one last thing to make this work if anyone else is having issues....
Go to `RegistrationModel.php` and look at the first function `registerNewUser(){}`

It looks like this

```php
		// TODO this could be written simpler and cleaner
		// clean the input
		$user_name = strip_tags(Request::post('user_name'));
		$user_email = strip_tags(Request::post('user_email'));
		$user_password_new = Request::post('user_password_new');
		$user_password_repeat = Request::post('user_password_repeat');
		
		// stop registration flow if registrationInputValidation() returns false (= anything breaks the input check rules)
		$validation_result = self::registrationInputValidation(Request::post('captcha'), $user_name, $user_password_new, $user_password_repeat, $user_email);
		if (!$validation_result) {
			return false;
		}
```

We need it to be like this to determine the proper post name which depends on which captha type you are using.
```php
		// TODO this could be written simpler and cleaner
		// clean the input
		$user_name = strip_tags(Request::post('user_name'));
		$user_email = strip_tags(Request::post('user_email'));
		$user_password_new = Request::post('user_password_new');
		$user_password_repeat = Request::post('user_password_repeat');
		
                // THIS IS THE SWITCH! :)
		if (Config::get('RECAPTCHA_ENABLED')) {
			$captcha = Request::post('g-recaptcha-response');
		}else{
			$captcha = Request::post('captcha');
		}

		// stop registration flow if registrationInputValidation() returns false (= anything breaks the input check rules)
		$validation_result = self::registrationInputValidation($captcha, $user_name, $user_password_new, $user_password_repeat, $user_email);
		if (!$validation_result) {
			return false;
		}
```

Don't overlook this minor change in the above code
from
```php
$validation_result = self::registrationInputValidation(Request::post('captcha').....
```
to
```php
$validation_result = self::registrationInputValidation($captcha......
```
Hope this helps :)

**Comment by di48l069** [comment]
@panique  Will this feature be implemented in next release it is really Awesome :+1:

**Comment by panique** [comment]
Hey, this is linked from the readme now, but I think it's better to simply leave this as a ticket instead of implementing it by default (as this would become tricky with the additional composer-dependency that wouldn't be needed by 90% of the users)... hmm... hard decision...

Anyway, users who read the readme will find this :)

**Comment by ChristianGrieger** [comment]
Looks like the code base got a bit changed? Would you be so friendly to explain exactly how i can add recaptcha to the register page? :) (So what exactly i have to replace) Thank you very much.

**Comment by DonMcCoy** [comment]
Along with those changes I have fork a copy and implemented reCAPTCHA:
https://github.com/donmccoy/huge
