### ISSUE TITLE
Avatars upload. .htaccess extra

### ISSUE THREAD

**Issue by tankerkiller125** [panique/huge#667]
It would probably also be safe to add `php_flag engine off` to the avatars. Htaccess as it would completely disable the php engine in that directory.

**Comment by panique** [comment]
Thanks, it's now in develop branch

**Comment by Punchlinern** [comment]
This isn't supported by all php modes, at least FastCGI and suPHP **doesn't** support php_flag in the .htaccess-file.
When the avatars are requested the server responds with a 500 error, logging:
*Invalid command 'php_value', perhaps mis-spelled or defined by a module not included in the server configuration*
Maybe [this](http://stackoverflow.com/questions/18932756/disable-all-cgi-php-perl-for-a-directory-using-htaccess) might be an option?

**Comment by Punchlinern** [comment]
After some more googleing and testing I found that the solution from my link in my previous wont work either. It seems that you have to set php_flags in a php.ini-file. In this case a custom one in the folder itself. (I haven't got that working yet, either, but that probably hasn't got anything to do with this project.)
