### ISSUE TITLE
Using with Request with Angular's $http

### ISSUE THREAD

**Issue by mwils-bp** [panique/huge#677]
I'm trying to do a post via ajax with Angular.js, I've tried using ```Request::get('source')``` and had no luck. I checked core/Request.php and saw its just using the standard ```$_GET``` etc.

Here is my method:

	public function save()
	{
	   var_dump($_GET, $_POST);
	}

Here is the post which is done via ajax.

	 var promise = $http({
		 method: "post",
		 url: url + "dashboard/save",
		 data: {
			"source": tool.source
		 }
	 });

	 return promise;

**Comment by oisian** [comment]
use Request::post('source') ??

**Comment by mwils-bp** [comment]
Nope that does not work either, I was trying that first but then I saw $_POST is used in ```core/Request.php``` anyway.

Could it be something to do with the header of the AJAX request?

**Comment by panique** [comment]
Hey, have a look here: https://github.com/panique/huge/blob/master/application/core/View.php

The normal `render()` in a controller method render the view WITH header and footer, this might be your problem (however i have absolutly no idea what "it does not work" means). For ajax actions simply use `renderJSON()`, this will do probably what you need :)

```
    /**
     * Renders pure JSON to the browser, useful for API construction
     * @param $data
     */
    public function renderJSON($data)
    {
        header("Content-Type: application/json");
        echo json_encode($data);
    }
```

**Comment by panique** [comment]
Btw I'll try to write a documentation but there's no time, you know, business business business :)

**Comment by mwils-bp** [comment]
Sorry if it isn't clear, my main problem is actually getting the data to that function from an ajax call.

Which is why I've been trying to use ```Request::get('source')```, to get the data which is sent via the ajax call.

I've took a look in the LoginController which uses ```Request::get('redirect')```, but thats being done from the form itself and not via ajax. When trying to use the same approach for ajax it does not receive the data.

Hope that clears it up a bit.

**Comment by panique** [comment]
When you send a POST request why do you grab the GET data ?

**Comment by mwils-bp** [comment]
Whoops thats a typo, I meant POST

**Comment by panique** [comment]
Any news on that ? Have you had success with this problem ?

**Comment by bribrink** [comment]
In a follow up, how are people generally handling ajax? I use a lot of
dynamic content.. through controller ->View->renderjson.
Is there a better practice?
Thanks for all you guys do!

**Comment by mwils-bp** [comment]
@panique I had no luck getting it to work with ```Request:post('source')``` and haven't discovered why.

But, I did manage to get it to work using ```file_get_contents('php://input')```:

    public function renderInput()
    {
        echo json_encode(file_get_contents('php://input'));
    }

**Comment by bribrink** [comment]
Are you trying to grab HTML?

**Comment by panique** [comment]
@mwils-bp Some ideas:

1. Can you try an ajax call with pure native JS, if this works then it's probably something on Angular-side.

2. Maybe it's a cross-domain-security-thing, you know, there's a cookie inside the project that prevents cross-domain-cookie-usage (=cookie is only visible for exactly the defined domain), but this feature is currently only in the develop-branch, not in the master. Can you say which one you used ?

Have a look here for the lines I mean: (line 287)
https://github.com/panique/huge/blob/b2e1b824e2f5f99eb1e9e67830114f982c121d39/application/model/LoginModel.php#L287

Also have a look here (Marks the cookie as accessible only through the HTTP protocol. This means that the cookie won't be accessible by scripting languages, such as JavaScript.):
https://github.com/panique/huge/blob/develop/application/config/config.development.php#L26

Maybe this has something to do with it...

**Comment by ikwijaya** [comment]
see https://github.com/ikwijaya/AM
