### ISSUE TITLE
Vendor folder gone?

### ISSUE THREAD

**Issue by Punchlinern** [panique/huge#678]
I'm sorry, this feels like a really stupid question, but I just can't figure it out. Where did the 'vendor' folder go? From what I can gather many files in there are still vital?

**Comment by panique** [comment]
??? He, there is no vendor folder in this repo (and any other PHP project), the vendor folder is created by Composer which fetches your dependencies. 

Btw I've written a small tutorial on exactly this (What is Composer), maybe this is what you need: http://www.dev-metal.com/composer-tutorial/

**Comment by Punchlinern** [comment]
I knew I'd missed something obvious! Thanks!
I'm making a transition from an older version of you php-login-advanced which had the folder included(?)

**Comment by panique** [comment]
Sorry i dont know what you mean. php-login-advanced has nothing to do with this script here and there's also no vendor folder in it.

**Comment by Punchlinern** [comment]
I'm gonna stop bothering you after this!
A project I'm working on is based on php-login-advanced, but I'm going to change it to be built on HUGE instead. 
I cloned php-login-adv like 1.5 years ago, and I thought the vendor folder was included then (I can't remember having used Composer before), but maybe I'm mistaken. Not that it matters now.
Anyway, thanks for your amazing work!
