### ISSUE TITLE
[feedback message] For User Name Does Not Exist

### ISSUE THREAD

**Issue by mcanatalay** [panique/huge#679]
I recently traverse whole code. I have discovered a little gap. In LoginModel we have a wrong type of feedback. I know you don't want to give any specific data to attacker. But in line #103 passed feedback message is FEEDBACK_LOGIN_FAILED_3_TIMES. There should be a FEEDBACK_USERNAME_OR_PASSWORD_WRONG type feedback. It is also applicable to whole FEEDBACK_PASSWORD_WRONG error messages.

Also FEEDBACK_LOGIN_FAILED should really be removed. 2 error messages is really anoying if one of them is same in all times.

**Comment by oisian** [comment]
Fix it and send a pull request :) well spotted

**Comment by panique** [comment]
Thanks, has been fixed now (in develop and master branch)!
