### ISSUE TITLE
redirect issue with checkAuthentication()

### ISSUE THREAD

**Issue by lkissorban** [panique/huge#681]
The redirect is not working after login, as the url is duplicated.

Solution:
in config.php a new line after 'URL' definition:
  'BASE_URL' => str_replace('public', '', dirname($_SERVER['SCRIPT_NAME'])),
in Auth.php change the header() line to:
  header('location: ' . Config::get('URL') . 'login?redirect=' . urlencode(substr($_SERVER['REQUEST_URI'],strlen(Config::get('BASE_URL')))));

L

**Comment by panique** [comment]
Sorry I don't understand the problem to be honest. Can you go into detail what "the url is duplicated" means ? THanks!

**Comment by lkissorban** [comment]
Test it...

1) Login to the app, go to the dashboard, which accessable only when you are logged in. Copy the url...
2) Log out.
3) Paste the dashboard url and send it.
4) You will be redirected to the login screen, with the dashboard url as requested screen.
5) After log in again, the url will be this:
http://localhost/projects/huge-master/projects/huge-master/dashboard/index
and it"s resulted as a 404 error...

L

**Comment by Dominic28** [comment]
That's a problem if you install the script in subfolders only.
A quick solution would be to manually filter out the subfolder from $_SERVER['REQUEST_URI'] in the Auth class. But I got no idea right now to solve this for everyone.

**Comment by lkissorban** [comment]
It was a nice improvement to automatically follow the subdirectories by the config, so I tought it will be usefull, if the redirect process fits itself also. But anyway, it's a nice framework, and helps me a lot in my small projects.
Thx

**Comment by panique** [comment]
@lkissorban Okay, I see, but this problem only exists when you don't install the framework properly! Usually an application will not have something like "/projects/huge-master/projects/huge-master/" inside the URL.

But to be fair, you're right, this is definitly not optimal for people who want to install it inside a subfolder. Hmm, let's put this on the TODO-liste, maybe someone has a really good solution here!

Can I ask you: Are there any other problems beside this redirect when using huge in a subfolder (i mean, when the URL has the subfolder inside) ?

**Comment by lkissorban** [comment]
No, it's working fine in a subfolder.

**Comment by mcanatalay** [comment]
Here what have I done for this issue,

First as you suggest I added base_url to config,
```php
'BASE_URL' => str_replace('public', '', dirname($_SERVER['SCRIPT_NAME'])),
```

I added two function to Redirect Class
```php
    /**
     * To the defined page
     *
     * @param $path
     */
    public static function back($redirect){
        header("location: " . Config::get('URL') . ltrim(urldecode(Request::post('redirect')), '/'));
    }
    
    /**
     * Get current page which you wanted to redirect later
     *
     * @return $path
     */
    public static function get(){
        return urlencode(substr($_SERVER['REQUEST_URI'],strlen(Config::get('BASE_URL'))));
    }
```

How to use it? Well, first get() will give you url of current page which you will redirect after login or a post request. back() will take this get() value if you want and redirect you to that page.

Why have I done this? For simplicity. I don't like to use long length codes over and over again.

Here is my Auth class:
```php
Redirect::to('login?redirect=' . Redirect::get());
```

**Comment by panique** [comment]
Thanks, I'll link this issue from the readme troubleshooting section (and close this ticket), so people can find it easier.

**Comment by ChaIcuWo** [comment]
+1 for this simple solution! Seems to have solved the issue for me entirely.

To expand slightly for others, in the LoginController class  I replaced
```
$data = array('redirect' => Redirect::back(Request::post('redirect')) ? Redirect::back(Request::post('redirect')) : NULL);
```
with 
```
$data = array('redirect' => Request::get('redirect') ? Request::get('redirect') : NULL);
```
and in the Auth class replaced 
```
header('location: ' . Config::get('URL') . 'login?redirect=' . urlencode($_SERVER['REQUEST_URI']));
```
with
```
Redirect::to('login?redirect=' . Redirect::get());```
