### ISSUE TITLE
[INFO] Extremely interesting article about password resets (by Troy Hunt, security expert)

### ISSUE THREAD

**Issue by panique** [panique/huge#682]
Definitly worth to read (I haven't had the time to read the entire article yet), and I really would like to implement everything mentioned in this blog post, maybe others also would like to add something.

[Troy Hunt - Everything you ever wanted to know about building a secure password reset feature](http://www.troyhunt.com/2012/05/everything-you-ever-wanted-to-know.html)

Troy Hunt is a quite popular web security expert.

**Comment by panique** [comment]
This is the recommended password reset flow by Troy Hunt, and ooohhh yeah, HUGE has implemented in nearly exactly in that way :)

Possible improvements:
1. Don't show user directly if account exists or not, send an email that says "Account does not exist"
2. Implement the *optional* security check after user clicked the password reset link in the mail, like security question or even 2-factor-auth (sending SMS to mobile device, sending email to other email account etc)

![password-reset5](https://cloud.githubusercontent.com/assets/156321/8814347/a7d08e72-300b-11e5-9cee-1dd4370b37e2.png)

**Comment by abmmhasan** [comment]
A great to read article. I'll read it later soon!

**Comment by abmmhasan** [comment]
So, summarized, and according to figure above it is as below,
1. Alwayse use one way / hashing to store password
2. Never remind password, but reset it
3. Never show username on site while requested for existence or forget password, rather ask for mail and tell 
"We have sent an email to your mail address with further instruction
The eamil will let you recover your username or other required infos"
4. Alwayse send a reset URL for forget password fact
5. Use captcha
6. Once user follow reset url, ask for secret question
7. Secret question should be concise, specific so it's answer become diversable, hard to discover, and constant over time,
8. Use 2-Factor Authetication
9. Reset password via mail address, not using username
10 IP record/Browser finger print for the password reset requesting agent/user
11. Notify that the password has been changed to mail with details of fingeprint (not password)
12. Be assure about security of used 3rd party login system

**Comment by panique** [comment]
I'll close this ticket as this is now linked from the readme (under "useful links")
