### ISSUE TITLE
Update Wiki to reflect more current information.

### ISSUE THREAD

**Issue by tankerkiller125** [panique/huge#685]
I noticed that the wiki articles are a bit outdated (since PHP 5.5 and 5.6 have both been released) Would be beneficial to maybe remove current wiki articles and make it more geared directly at this project.

Also it seems that the wiki is locked/broken as I can not add any pages (Was going to move my ReCaptcha support to the wiki where it could be sticky and not be considered an "issue")

**Comment by panique** [comment]
:) A full documention is in the making, but this will go public in october or later, not earlier (my job kills so much time).

I've also tried to make the wiki pages editable but this doesnt seems to work ... hmmm..
