### ISSUE TITLE
[improvement] Put changelog, version and plans into readme file

### ISSUE THREAD

**Issue by abmmhasan** [panique/huge#687]
Along with all other current information (+hot links)
1. Current change log
2. Current master branch version
3. Planned change log for upcoming version

**Comment by panique** [comment]
Good points! I'll definitly make this in the next time.

**Comment by abmmhasan** [comment]
First of all, don't mind my next questions! I just on an urgent quick project and wanna build it as updated as possible-
1. When will v3.2 release?
2. I haven't tested recent releases, does it include good routers?

**Comment by panique** [comment]
Hey,

3.2 will come up in september or october, but feel free to check out the develop (not so stable) or master branch (quite stable), it's currently 3.1 plus new features. Please note that it has breaking changes and you'll have to re-run the (changed) SQL files.

No, no good routers inside, just a super simple method that splits the URL and then calls the controller/method/parameter1/parameter2/etc

**Comment by panique** [comment]
I'll close this ticket for now, everything that is important will go into readme, and changelog needs to be a single file, this is some kind of standard in the github world. Releases and plans will no go into readme for sure! :)
