### ISSUE TITLE
[question] Forms inside admin/index table not working

### ISSUE THREAD

**Issue by afermon** [panique/huge#690]
HTML allow only td, th as child elements. As a result, those forms don't work (At least in chrome).
I fixed by using the main form inside the ID column and using the form="formid" in each input element.

However, i guess this solution only works on HTML5

BTW: I'm using other css styles

```php
<td><?= $user->user_id; ?><form id="f<?= $user->user_id; ?>" action="<?= config::get("URL"); ?>admin/actionAccountSettings" method="post"><input type="hidden" name="user_id" value="<?= $user->user_id; ?>" /></form></td>
<td class="avatar">
        <?php if (isset($user->user_avatar_link)) { ?>
                <img class="circle responsive-img" src="<?= $user->user_avatar_link; ?>"/>
        <?php } ?>
</td>
<td><?= $user->user_name; ?></td>
<td><?= $user->user_email; ?></td>
 <td data-l10n-id="<?= ($user->user_active == 0 ? 'No' : 'Yes'); ?>"></td>
<td><a data-l10n-id="Profile" class="btn" href="<?= Config::get('URL') . 'profile/showProfile/' . $user->user_id; ?>"></a></td>
<td><input form="f<?= $user->user_id; ?>" type="number" name="suspension" /></td>
<td><input form="f<?= $user->user_id; ?>" id="d<?= $user->user_id; ?>" type="checkbox" name="softDelete" <?php if ($user->user_deleted) { ?> checked="checked" <?php } ?> /><label  for="d<?= $user->user_id; ?>"></label></td>
<td><button form="f<?= $user->user_id; ?>" type="submit" class="btn waves-effect waves-light" data-l10n-id="Apply"><i class="material-icons"></i></button></td>
```

**Comment by panique** [comment]
He afermon, hhmmm I'm confused now, these forms worked perfectly for 2 years, and you can easily check this in the live-demo for sure. I'm doing this for 15 years now and have never seen something like `<input form="f<?= $user->user_id; ?>`, this is definitely not standard, and I'm sure this will not in all browsers!

In all tests all tables worked perfectly and all tables just used the most simple standard implementation possible, standard 

```
<form>
  <input .... />
</form>
```

Maybe I'm missing something here and I'm totally wrong, so can somebody else please have a look on this ? Thanks! :)

**Comment by afermon** [comment]
Hi, actually that comes with the HTML5 standard and and it's called form-associated element and can have an form-owner. As shown here http://www.w3.org/TR/html5/forms.html#form-owner and http://www.w3schools.com/tags/att_input_form.asp
```HTML
<form action="demo_form.asp" id="form1">
  First name: <input type="text" name="fname"><br>
  <input type="submit" value="Submit">
</form>

Last name: <input type="text" name="lname" form="form1">
```
However this is not working on IE

Thanks!
