### ISSUE TITLE
Another Branch: CMS

### ISSUE THREAD

**Issue by abmmhasan** [panique/huge#694]
Has long been thinking, What about a complete CMS version? I mean a blog, forum, Profile.....

**Comment by oisian** [comment]
Focusing development on another direction for the project would be completely out of line of what this project is, which is a well put together login framework,  i personally feel like it would make no sense to then take it and focus it to a CMS, Blog or what ever, certainly in this repo anyway. that's my opinion anyway

**Comment by panique** [comment]
Yeah i would also agree with @oisian , there are good CMS out there (for example [October](https://octobercms.com/) which has even Laravel under the hood), and it would take lots of work to create a new one. To be honest I'm already totally overworked with this one here, so a CMS is - from my side - not possible.

But, feel free to fork the project for sure and do whatever you like :)
