### ISSUE TITLE
Report possibly security problem

### ISSUE THREAD

**Issue by Caradryel** [panique/huge#696]
Hello everyone

I wanted to report an issue which might be an security problem.

In the project description security bugs are asked to be reported by email:
"I'd kindly ask you to send really big bugs to my email address, not posting this here"

But I can not find an e-mail contact. I have also checked the Blog (http://www.dev-metal.com) and did not find a contact.

Where should I post/send the issue to?

Thanks in advance

**Comment by panique** [comment]
He @Caradryel , thanks a lot, please send an email to panique@web.de (was removed from my profile as too many spam came up).

Thank you also for doing this the professional "responsible disclosure" way :)
