### ISSUE TITLE
[INFO] interesting article about authenticating via sound (!)

### ISSUE THREAD

**Issue by panique** [panique/huge#698]
Super-interesting concept: Logging in via sound / environment noise, article is in german (currently searching for an english version):
http://t3n.de/news/zwei-faktor-authentifizierung-mal-631692

Spontaniously I see a lot of potential weirdness and security issues here but it's a interesting concept, no question.

**Comment by abmmhasan** [comment]
That article has some info, not enough though. Well, I'm currently working on several Multi-step authentication solution. Already made 2 type of them. Voice recognition type one has several problem. First of all 2 device might act differently in different different environment. For suppose in an A. C. room you might see a type of difference but in non-A.C. it may go different. 
2ndly, If you think about detecting sound I've tried some. But, problem will happen as they don't have Tone detection (whether we can differentiate same word spoken by 2 person....).. My project get paused for this. Though I started working on another as I haven't seen good hope in it...
