### ISSUE TITLE
(Question) Creating Pages Outside of the Controller

### ISSUE THREAD

**Issue by videsignz** [panique/huge#699]
I am new to the world of MVC and have explored HUGE quite extensively and can understand how it all works for the most part.

I have a question though.

The Issue:
First off...Say I have a set of pages that are the base of my website (Public Pages) such as **About Us, Contact Us, Products, Services** and so on. It seems a bit overkill to have to write Controller Functions for all of these "Public Pages" especially when the number of pages could be many.

Secondly...when visiting a page such as **mydomain.com/contact** it seems a bit unappealling to have to have a controller name in there (ie: **mydomain.com/controller/contact**).

My Attempt:
With a bit of messing with the **`core/application.php`** file, specifically in the **`else`** statements that normally push a 404 page, I created a function to check if an actual page exists, and if so to require that page instead of showing a 404. Works perfect...*BUT.*..I lose all access to the Huge Classes.

I still need the classes available to take advantage of a couple of the **`LoginModel::function()`** functions to display a user bar at the top of each page and to also use the *loginWithCookie* function.

Ideas:
So, I am wondering what I can do to solve this.
My Idea is to have some sort of `special/` folder that allows any page inside of it to have access to the classes yet would not need to be rendered by a controller. Along with that, a mod rewrite that would mask the `special/` folder to take something like **mydomain.com/special/contact.php** and show it as **mydomain.com/contact.php**

Note:
I am a new member to Github (signed up just to ask this question) and can not figure out how to tag this as a question. I also do not know if this is the right place to post a question. I apologize if it is not.

Thank you Panique for the awesome work you have put into this project!
Maybe I am overlooking an easy way to achieve this, or even overthinking it...any ideas would be great!

**Comment by videsignz** [comment]
As an added idea, apart from the above, it seems like the dashboard views/controller should contain all of the show/change/edit features found in the login section. Leaving the login functions clean and simple, only showing the pages necessary to sign in/register/and verify. Make sense?

**Comment by ajborn** [comment]
I think most of what you mentioning is preference.

You should always keep to the architecture of the framework and use a
controller to render all pages. Even if they do not have functionality.

What if you need to secure one of those pages in the future for logged in
users?

Having the page rendered from the controller allows for you to access those
functions easily.

Also having the pages rendered from a controller allow the header and
footers to be used dynamically.

The way you recommend breaks architecture and black boxes pages.

If your not much of a back end programmer, I recommend word press.

**Comment by videsignz** [comment]
@ajborn Thanks for the input. Though the WordPress comment seems a bit snarky. Just because I see a preference to detach certain pages from the MVC and still have access to certain classes does not mean I am not a back end programmer...it just means I think a bit different.

Aside from the separation 'preference', is it not legitimate to desire a set of pages that appear to be in the root of a site, not showing the controller name? Seems to me that implementing a switch based on a controller name is possible and not outside the architecture of an MVC.

Hopefully your reply won't be condescending next time.

**Comment by panique** [comment]
Hey there,
thanks for the nice feedback ! :) Always good to hear.

Regarding your questions: Good point, creating something like /contact or /about-us is tricky, you'll have to create a new controller for it or in case of About Us even find another name or rewrite controller-names / method names (as PHP does not allow `-` dashes inside a method/class name, a simple str_replace or trim() will do the job.

The including of .php files is definitly not the way to go, this is simply not how frameworks work, sorry! If you really need to do that try to rewrite the content of these files into the controllers, models and views, spontaniously I really don't have a better solution. Even if this takes you more time, in the end it's better for everybody as mixing framework logic and "own" logic will only bring you into big problems.

And please let me say this: HUGE is not a really good framework when it comes to framework logic! The main purpose of this project is the ready-to-go login part, most other frameworks are much much better when it comes to architecture.

**Comment by videsignz** [comment]
Thanks for the reply @panique 
I am ok with keeping all the pages within the framework...not a big deal. Having the url always contain the controller name is something I will keep working on. I did find an actual issue I encountered that I will post shortly regarding the `Auth::checkAdminAuthentication();` and an infinite loop.
