### ISSUE TITLE
[Improvement] Use dependency injection.

### ISSUE THREAD

**Issue by djsmithme** [panique/huge#703]
For example of the mail class you could do something like:

```
interface MailInterface{
    public function sendMail($user_email, $from_email, $from_name, $subject, $body);
}

class NativeMailer implements MailInterface{

    public function sendMail($user_email, $from_email, $from_name, $subject, $body){

        $headers = 'From: '.$from_email. "\r\n" .
            'Reply-To: webmaster@example.com' . "\r\n" .
            'X-Mailer: PHP/' . phpversion();

        return mail($user_email, $subject, $body, $headers);
    }

}

class Mail implements MailInterface{

    public $mailer = null;

    public function __construct($mailer){
        $this->mailer = $mailer;
    }

    public function sendMail($user_email, $from_email, $from_name, $subject, $body){
        $this->mailer->sendmail($user_email, $from_email, $from_name, $subject, $body);
    }


}

$mail = new Mail(new NativeMailer());
$mail->sendMail('user','from','name','subject','body');

```

**Comment by panique** [comment]
What would be the advantage over the current implementation ? Please keep in mind that this is not a really professional framework, just a quick login implementation, not focussed on framework architecture.

**Comment by djsmithme** [comment]
Currently you have PHPMailer as a dependancy added to the main Mail class with additional methods that do not have any code (as examples i take it). You could easily remove them, make the class smaller and then inject the mailing script of choice. The main advantage would be DRY as well as not having a hard coded dependancy in your application making switching out mailers (going foward) a lot easier. if you where looking to streamline for production you could also remove these classes from your final application.

This is an 'here's an idea' type issue not a 'you should do this' so either way :)

**Comment by panique** [comment]
Thanks, this would be a good improvement, but I think it's out of scope of the main idea behind the project, and I'm totally out of time for this! Please let's keep this script as simple as possible and skip improvements like this for now.

I hope that's okay for you!
