### ISSUE TITLE
[TO CLARIFY] Account Re-Verification on Email Change

### ISSUE THREAD

**Issue by videsignz** [panique/huge#705]
I was thinking...
If we use email verification for an account on creation, why would we not do the same when a user changes their email?

To me this only makes sense. It could go something like this...
1. User changes email and is logged out
2. User DB status changes back to inactive
3. Email resent to verify
4. Link clicked to reactivate

Obviously there should be some sort of notification shown to the user alerting them that their account will be set back to inactive.

Thoughts?

Here is a quick setup for the function (Not tested)

```php
    public static function saveNewEmailAddress($user_id, $new_user_email)
    {
        $database = DatabaseFactory::getFactory()->getConnection();
		$user_activation_hash = sha1(uniqid(mt_rand(), true));

        $query = $database->prepare("UPDATE users SET user_email = :user_email, user_active = :user_active, user_activation_hash = :user_activation_hash WHERE user_id = :user_id LIMIT 1");
        $query->execute(array(':user_email' => $new_user_email, ':user_active' => 0, ':user_activation_hash' => $user_activation_hash, ':user_id' => $user_id));
        $count =  $query->rowCount();
        if ($count == 1) {
			if(RegistrationModel::sendVerificationEmail($user_id, $new_user_email, $user_activation_hash, true)){
                LoginModel::logout();
                Redirect::home();
			}
        }
        return false;
    }
```

**Comment by panique** [comment]
Hmm interesting! This means the account would be inactive until the user confirms the new email.
Good idea, but i see some problems, like when you accidentially mistyped the new email then there will be no way to ever get back into your own account.

**Comment by slaveek** [comment]
Two email inputs.
- type new email
- retype new email
This can be easiest.

**Comment by OmarElGabry** [comment]
Good point! I see the following solution could be appropriate:

1. Whenever the user asks to change his email(or passwords, or any critical information), ask the user to enter his credentials again.
2. As for updating the email, as @slaveek said you can ask the user to enter the new email, and confirmation, this will reduce mistakes by user.
3. Your application in turn will update the user's email, regenerate email_token, and set user_active to false.
4. Your application will then send an email for the new email asking the user to verify it, and another notification email to the old email asking the user to report or revoke the changes if needed.
5. If the user reported or revoked the changes, ask the user to change his password - this is critically important.
6. And It doesn't go without saying, If you application updated the database and set the user's new email, but **failed** to send both emails, you need to revert back to old state, and output an error message.

**NOTE** I'll keep this comment updated whenever something better, or if i found a security hole in the above steps.

**Comment by slaveek** [comment]
@OmarElGabry 
>
Your application will then send an email for the new email asking the user to verify it, and another notification email to the old email asking the user to report or revoke the changes if needed.

I think that two emails shouldn't be send the same time. If someone use verification link in new email first then will be to late to revoke changes.
I can see that in a bit different way:
- send request changes link to old email (with warning and possibility to cancel) 
- open change email form asking user for password
- when user click on change email button, deactivate account and send verification link to new email address
- click on verification link in new email

**Comment by OmarElGabry** [comment]
@slaveek  
> If someone use verification link in new email first then will be to late to revoke changes.

Nope, you can revoke it, the application will simply checks the url coming user's old email which asking for revoking, this url should have some sort of identification for the current user.

If so, then update the current user's email, and replace it with the old one. Also you **have to** ask the user to change his password, as i said before, this is critically important.

It don't see a big difference, in both ways you are going to send email to new and old user's email one after another.

**Comment by panique** [comment]
Btw if the user really mis-spelled the email adress then it's still possible to login with username.

**Comment by videsignz** [comment]
@panique that is spot on, It would simplify implementing this as well.

**Comment by panique** [comment]
As this is a good, but also a very advanced feature and would bloat the project quite much I would kindly close this ticket, but link to it from the readme, so people who really need this feature will still find this ticket.
