### ISSUE TITLE
[Question] "Using $this when not in object context" when using this MVC, any pointers? Thanks!

### ISSUE THREAD

**Issue by kenens123** [panique/huge#710]
I'm constantly getting the error "Using $this when not in object context" whenever i try to load a page with the huge framework that uses something like this (example):
<?php $this->renderFeedbackMessages(); ?>

Anyone know what the issue is and possibly know how to fix it? 

I'm using php version 5.5.12 & WAMP.

Thanks in advance!

**Comment by panique** [comment]
Is this about the code in the framework itself or just when you add code written by yourself ?

**Comment by kenens123** [comment]
the code in the framework itself

**Comment by videsignz** [comment]
Are you loading the page via a render command, such as `$this->View->render(index/index);`?

**Comment by panique** [comment]
As you can see in the live-demo this works without any problems. Might be a problem on your side.

**Comment by kenens123** [comment]
Well.. i'll have a closer look, appreciate the feedback my front, sorry for bothering you, thanks!

**Comment by videsignz** [comment]
You should note, that using $this within a static function is not allowed.
Static functions are declared like this
```php
public static function myFunction(){
    // You can not use $this within this function
}

**Comment by curielmc** [comment]
I got the same exact error using XAMP. Any additional insight?

**Comment by panique** [comment]
@curielmc Can you reproduce the error when installing this correctly in a real LAMP stack like described or with the autoinstaller ? I'm unsure if this is a real bug or just something with broken installations

**Comment by kenens123** [comment]
@panique i'm using WAMP, but that's besides the point, i think there may indeed be something wrong with the installation files, i've tried cloning it several times without anything added & running composer but i still get he $this while not in object context error, appreciate the feedback my friend!
