### ISSUE TITLE
[SOLVED!?] Prevent Curl Views without Exit() and with added security backup

### ISSUE THREAD

**Issue by videsignz** [panique/huge#711]
Well, it took me all night and today to come up with, what  I believe, is a real sound solution.

**Auth Class**
We start by replacing the `exit()` function with the following.
```php
// Initialize a new Session
Session::init();
// Set a session 'Restrict' flag
Session::set('restrict', true);
```
The `header('location')` function has already been called at this point so the above script would presumably only affect a curl request. Easy enough...

**View Class**
In my understanding, it is ultimately the view that we need to protect.

We begin by adding a new function called `clean($filename)` (we can name it better later on)
Refer to the comments in this script for an understanding of the function...
```php
public static function clean($filename)
{
	// If the restrict flag is set to true
	if(Session::get('restrict')==true){
		// Change the $filename to another page
		$filename = 'login/index';
		// Destroy the Session as it is no longer needed
		Session::destroy();
	}	
	// Return the $filename to render
	// restrict=true $filename='login/index';
	// else $filename=original $filename;
	return $filename;		
}
```
Finally, in all of the render functions that will be used to render secured areas you would call this function first and foremost.
```php
public function render($filename, $data = null)
{
    // Here is the call
    $filename = self::clean($filename);		
				
    if ($data) {
        foreach ($data as $key => $value) {
            $this->{$key} = $value;
        }
    }	
    require Config::get('PATH_VIEW') . '_templates/header.php';
    require Config::get('PATH_VIEW') . $filename . '.php';
    require Config::get('PATH_VIEW') . '_templates/footer.php';
 }
```
As you can see, we completely avoid using the `exit()` function and mimic the effect of the original `header("location")` function

The beauty of this is that it only gets initiated if the script runs past the header redirect, via curl, or for any other unforeseen reason. Nice backup either way :)

I have tested this in all ways possible that I know of, but if any of you could break this, please tell me so.

I would really like to know what you guys think!

**Comment by videsignz** [comment]
I wanted to add another method, which I have been testing. This method would eliminate the `Auth` class and somewhat merge it with the `View` class.

If we add this function to the `View` class
```php
    public function authorize()
	{
		if(!Session::userIsLoggedIn()){
			// Destroy the Session as it is no longer needed
			Session::destroy();
			// Redirect for Browsers
			header('location: ' . Config::get('URL') . 'login?redirect=' . urlencode($_SERVER['REQUEST_URI']));
			// Redirect for Curl
			return $this->render('index/signin');		
		}else{
			return $this;
		}
	}
```
We can then call it like so within the controllers (Method Chaining)
```php
	$this->View->authorize()->render('note/index', array(
		'notes' => NoteModel::getAllNotes()
	));
```
Instead of like this
```php
    Auth::checkAuthentication();
	$this->View->render('note/index', array(
		'notes' => NoteModel::getAllNotes()
	));
```
There are few benefits...
1. Less code with the elimination of the `Auth` class
2. No need to hard `exit()`
3. Implementation is one line instead of two

Any feed back would be great!

**Comment by panique** [comment]
Thanks, looks really clever, I'll do some heavy tests with this :)

**Comment by panique** [comment]
Hey there, unfortunatly everything needs to be protected, not just the view! Every line of code in the entire application should only be reachable if the user is logged in and has the according rights/rule.

Sorry to say this, but the code above does not handle this. Even if we don't show views at all, everybody would still be able to do stuff on the application by simple using the "correct" URL.

**Comment by panique** [comment]
I'll move this issue to the general todo list in the readme btw

**Comment by videsignz** [comment]
Hi Chris, I did a good amount of testing with my first suggestion. Can you give me an example of how you were able to access restricted areas using curl with a 'correct' url?

**Comment by videsignz** [comment]
Also, I have another way of doing it which I am using on my app which may be suitable but after your last comment, I am not sure if the result would be the same as you just described.

**Comment by panique** [comment]
Hi, when you have a controller-action like

```public function doStuff() {
    
    doOneThing();
    andAnother();

    $this->View->authorize()->render('note/index', array(
        'notes' => NoteModel::getAllNotes()
    ));    
}```

then the authorize stuffw works on the view, but totally skips everything that's made inside the controller, like changing data, deleting stuff, you know

**Comment by videsignz** [comment]
Ahhh....right, that makes sense when regarding my second suggestion using `$this->View->authorize()->render();`

**Comment by panique** [comment]
I hope this is okay for you, as this project is mainly a security thing, at I think when rebuilding the auth logic behind then it should be in very little steps, with very little changes and with extreme testing.

I'll put this ticket and your code on the long-term-fix list, but currently this is not really necessary, so please let's skip it for now :)

**Comment by videsignz** [comment]
Ok, I understand your thinking.... I may post some other suggestions in the future though ;)

**Comment by videsignz** [comment]
Maybe there should be two base controller classes, one is unprotected 'Controller' and the other is 'ProtectedController' and within all extended classes of the protected controller you set all methods to private. In the 'ProtectedController' you would have a __call function that checks if the user has the proper rights, if they do no not, then you point the controller to a default method that does nothing but render a default page.

**Comment by videsignz** [comment]
I did this with my View class like so....

	`public function __call($name, $arguments){	
		
		if(!Session::userIsLoggedIn() && Session::get('restricted')==true) {
						
			Session::destroy();
			$this->$name('index/signin');	
					
		}else if(Session::userIsLoggedIn() && Session::get('restricted')==true) {
			
			$this->$name('dashboard/index');
						
		}else{
			
			if(isset($arguments[1])){
				
				$this->$name($arguments[0], $arguments[1]);
				
			}else{
				
				$this->$name($arguments[0]);
				
			}
		}				
	}`

**Comment by videsignz** [comment]
But since we need to protect more than the view, this isn't a full solution, just a potential road map.

**Comment by videsignz** [comment]
I should mention, this only takes effect if the Session variable Restricted is true. And this only happens after the Auth redirect so would only affect Curl users.

**Comment by panique** [comment]
We definitly need to protect everything! The view is just the tiny part for the end-user. As in the example above, a controller like

```
public function deleteUser($id) {

    deleteUser($id);

    $this->View->authorize()->render('note/index', array(
        'notes' => NoteModel::getAllNotes()
    ));    
}
```

would be callable by everyone, not just by a logged in user and allowing everybody to delete everything :(

**Comment by panique** [comment]
Please don't change this project if it's not absoltuly necessary! I spend so much time fixing changes that are not really necessary and break things, maybe it's better to just move on in very small steps.

**Comment by videsignz** [comment]
Don't worry, I am not submitting pull requests to the repository. These are just things I use in my app and work perfectly. And like I said, I realize it only protects the view. I still use the Auth class as intended. I just add a session restricted flag if someone passes the redirect.

**Comment by videsignz** [comment]
And I scrapped this `$this->View->authorize()->render();` a long time ago, I still use the `Auth::checkAuthentication();`
