### ISSUE TITLE
FEEDBACK_LOGIN_FAILED_3_TIMES at first wrong login

### ISSUE THREAD

**Issue by Caradryel** [panique/huge#713]
Hello everyone

I notized, that everytime I log in with a not existing user I get the message for      FEEDBACK_LOGIN_FAILED_3_TIMES

I checked the Login-Model and found
           Session::add('feedback_negative', Text::get('FEEDBACK_LOGIN_FAILED_3_TIMES'));
in row 103.

There is no check for 
          Session::get('failed-login-count') >= 3 AND (Session::get('last-failed-login') > (time() - 30))
in this case.

Is this a bug or did I miss something?

Thanks in advance

**Comment by OmarElGabry** [comment]
Yes, I noticed the same thing. It should be something like "Email & Password combination doesn't exist" in [Line 103](https://github.com/panique/huge/blob/master/application/model/LoginModel.php#L103)

**Comment by OmarElGabry** [comment]
Yes, I noticed the same thing. It should be something like "Email & Password combination doesn't exist" in [Line 103](https://github.com/panique/huge/blob/master/application/model/LoginModel.php#L103)

**Comment by panique** [comment]
It's fixed in develop and master branch, please comment if you still have this or a similar issue!
