### ISSUE TITLE
How to change Notification in PHP login Advance 

### ISSUE THREAD

**Issue by vijendermaan** [panique/huge#716]
After i submit the form i got a :
" Your account has been created successfully and we have sent you an email. Please click the VERIFICATION LINK within that mail."   , I want to change this notification text ... How can i change it ? 

If my id is already register message is showing :   "This email address is already registered. Please use the "I forgot my password" if you don't remember it.  "        How can i change it ?

When i successful activation  it' show me " Activation was successful! You can now log in! "  How can i change it ?

**Comment by panique** [comment]
Seriously ? 

1. What you write has absolutly nothing to do with this project (as you already figured out by yourself in the headline).

2. Okay you want to change a text inside your code. And that's a problem for you ? How about doing a full-text search inside the code, like every smart person would do ?

3. The other sentence you wrote is nearly unreadable, sorry.

**Comment by ajborn** [comment]
I like your response ;>
