### ISSUE TITLE
[QUESTION] Is there a best way to pupulate form fields after form submit?

### ISSUE THREAD

**Issue by ghost** [panique/huge#717]
Form validations in your framework huge-2.1.1 resets all fields results empty fields so user will have to type it again. Can you suggest a best way on how to fix that? I really like this framework good job anyways!

**Comment by panique** [comment]
Good question! This is a common issue in basically all frameworks and it depends how you (or the framework) handle the request.

This framework usually doesn't route post-requests to the same page, it will redirect from a form from /notes/index to /notes/create when you submit the create-form, and then handle the post data in /notes/create and send you back to /notes/index when finished. This is the Post-Redirect-Get-Pattern, used by many frameworks to prevent people from resubmitting stuff with F5 (and so other reasons).

Downside is exactly what you said: The content os $_POST is not known anymore after the request.

You can "fix" this by 

1. using a strong frontend validation (common way) or 
2. by passing $_POST to the route you came from, like `Redirect::to('note', $_POST)`, you'll have to rebuild the Redirect method for this, or
3. by putting the stuff into the $_SESSION or
4. into frontend-containers like HTML5's local storage or
5. you simply rebuild the framework a little bit and submit always to the same method the form is inside, so you'll always have $_POST available, like tihs:

(untested pseudocode)
```
    public function create()
    {
        if is a post request {
            // handle the post-stuff
            NoteModel::createNote(Request::post('note_text'));
        } 

        // and then always show the form
        show view here
    }
```

**Comment by slaveek** [comment]
You can save input value in $_SESSION like:
eg. register form
``` php
Session::set('input_user_name', $_POST['user_name']);
```
or
``` php
$_SESSION['input_user_name'] = $_POST['user_name'];
```
then in view
``` html
<input <?php if(isset($_SESSION['input_user_name'])) echo 'value="'. $_SESSION['input_user_name'] .'"'; ?> name="user_name" />
```
I did not test but should work.

**Comment by b3ns** [comment]
Normally I'm just reading all these interesting things here, but this is a point which I was thinking about too when setting up a project with HUGE, so this is my first post here. Hi :)

I just want to extend @slaveek 's answer a bit:
I'm using the same approach as of now and it's working fine so far.
The only thing you need to make sure is: unset/empty the session keys you used after the validation was successful.
And if you have a big form and want to store everything I would suggest storing the whole $_POST into Session with a loop.

**Comment by klrznemrmtl** [comment]
Thank you I'll try it later!

**Comment by klrznemrmtl** [comment]
It worked! I stored $_POST values in session variables then unset it after success form submit. Thank you guys! :)

**Comment by panique** [comment]
Hey, I'll close this ticket as it's not really about the main feature of this little framework (you know, it's about login / security). Also, this issue is a common thing in every web application and definitly too much to write code for.
