### ISSUE TITLE
[TODO][IMPROVEMENT] Some mail providers (Yahoo) might "click" the confirmation links via their auto-spam-scanners

### ISSUE THREAD

**Issue by vijendermaan** [panique/huge#721]
When i try to register, the confirmation email is sent but if i click the link in the mail the php-login page says: Sorry, no such id/verification code combination here... 

ANy help

**Comment by sidopufn** [comment]
I also have this issue. What happens is that on registration the email is sent, the database enters the user_activation_hash into the database and sets the user_active to "0" - - but then immediately thereafter something spontaneously happens where user_active is set to "1" and the user_activation_hash is set to NULL. It looks like function verifyNewUser is being run by itself spontaneously without the verification email being clicked. 

I have not gotten very far to trace the potential problem - I just googled it first to see if anyone else had the issue and ended up here. 

A thought - is it possible that email scanners or spam scanners open the email link?

**Comment by sidopufn** [comment]
Following up on the comment above, I redirected where the return click on the email activation confirmation goes, and the problem went away - - thereby confirming that the outgoing email spam filter from the hosting provider is clicking on the link on the outgoing email, which then activates the account. 

I will be rewriting the activation script to return the link clicker to a page that then requires another click to confirm activation.

**Comment by panique** [comment]
Thanks for the excellent feedback and the investigation, this is indeed an issue! I'll take some time to find a good solution and implement it in the next time.

**Comment by abmmhasan** [comment]
Or what about giving a reCaptcha 2.0 on activation page?

**Comment by panique** [comment]
The most simple workaround is to use a notification to the user, explaining exactly what happened, so I've added this text to the feedback message: 

*Sorry, no such id/verification code combination here! It might be possible that your mail provider (Yahoo? Hotmail?) automatically visits links in emails for anti-scam scanning, so this activation link might been clicked without your action. Please try to log in on the main page.*

**Comment by geozak** [comment]
Quick idea what if the page loaded by the email link made a javascript ajax request to another page or maybe the same page but with a post request. Then the return of the ajax request is the feedback message.
From what I read looking this up the spam filters are not loading and executing the pages they are just resolving redirections. So the ajax should not get executed by the filter.

sudo code:
```
verifyuser($id, $code) {
if (isset($id) && isset($code)) {
    if(Request::postCheckbox("id") || Request::postCheckbox("code")) {
        if($id === Request::post("id") && $code === Request::post("code")) {
            //do validation action
            echo //validation feedback
            exit();
        }
        else {
            echo //feedback validation credentials don't match
            exit();
       }
    }
    else {
         //modified view to display in the normal feedback spot something like
        //"Please wait processsing" and have a javascript ajax request make a post request back
        //to the page and change the text of the feedback.
         view->render($id, $code);
    }
}
else {
    //redirect
}
}
```
