### ISSUE TITLE
[Suggestion] make all profile editing forms happen in one page rather than different ones

### ISSUE THREAD

**Issue by di48l069** [panique/huge#722]
It will be cool if you could combine all profile views into a single view similar to github settings where you can edit your (avatar, password,email) in a single view and save changes.

Just a idea...

**Comment by panique** [comment]
Hey there, definitely a good idea, let's see if this makes things easier.

**Comment by di48l069** [comment]
:+1:

**Comment by JFJanssen** [comment]
That would be great.

**Comment by panique** [comment]
Hey, I'll close this ticket as it's not about the main concept of the script. Please don't get me wrong, it's just that there's so much to do and this is way out of my available time.

**Comment by di48l069** [comment]
@panique would of been nice if this was added because current way is rather messy but you right its not the concept of the script.

**Comment by panique** [comment]
This is not messy, it's clearly seperated per task. If this would be merged, people will open tickets and say: It's messy now, please seperate it! :) Whatever you do on the internet, you are doing it wrong.

If you really need this feature, then please write it and commit it to the project.

**Comment by di48l069** [comment]
@panique i apologize its not messy its just could be better i will apply it to my project when i have then i will submit a pull request you welcome to use it.

**Comment by panique** [comment]
Sounds very good :)
