### ISSUE TITLE
[TODO][IMPROVEMENT] Confirm email address in registration (to prevent typos by user)

### ISSUE THREAD

**Issue by di48l069** [panique/huge#723]
Hi, i think the sign-up form is lacking a confirm emailaddress input field this will help if user accidentally types in incorrect email-address

**Comment by panique** [comment]
He, sorry I don't know what you mean, can you please go into detail ?

**Comment by di48l069** [comment]
@panique in case user types in there email incorrectly they will never receive a verification email

So on sign up have a extra input field "confirm email-address" if email does not match the first input box "email-address" they will not be able to sign-up

Just like image below this is from facebook signup

![ssgsg](https://cloud.githubusercontent.com/assets/7794777/9904492/74c7832e-5c7e-11e5-9420-223d2bb5b342.JPG)

**Comment by panique** [comment]
Ah okay! :) Sorry I'm a little bit sleepy (too much Ouzo). I'll put this on the TODO-list!

**Comment by di48l069** [comment]
@panique Haha No problem sorry for my terrible English lol

**Comment by panique** [comment]
It's done in develop branch :)

**Comment by di48l069** [comment]
@panique Epic
