### ISSUE TITLE
Separate the actions from LoginController.php to other controllers for a better organization and logic

### ISSUE THREAD

**Issue by nitnelav1101** [panique/huge#726]
Hi! Firstly thanks for this great framework! I have a "small" suggestion to improve the organization and the "logic" of this framework. For the moment you have one controller called "login" that does  operations like showProfile, editUsername, editAvatar etc. These operations aren't related to login, and I think it would be better if we separate them in different controllers.

Example:
1) MembersController.php 
- index() -> action that will display a list with all members
Link: domain.com/members/index or domain.com/members
- showProfile($user_id) -> action that will display a single user profile
Link: domain.com/members/showProfile/1 

2) UsercpController.php (usercp = user control panel)
- index() -> action that will display info about current member and a mini-menu with links to editUsername etc.
Link: domain.com/usercp/index or domain.com/usercp
- editUsername()
Link: domain.com/usercp/editUsername
- editUserEmail()
- editAvatar()

... etc. (all actions related to editing user profile)

Also this change implicates other changes in the view folder.

**Comment by slaveek** [comment]
I think that this #549 is similar

**Comment by nitnelav1101** [comment]
Ups, my bad! @slaveek you are right, them are similar! I hope to see this in the new release, because I think that it will be very useful for everyone. :smile:
