### ISSUE TITLE
Router: Separated

### ISSUE THREAD

**Issue by abmmhasan** [panique/huge#727]
I've an intention to upgrade your routing! For this what I like in your code base is a fully separated "router.php" file. I mean, every routing will be controlled by router.php file. this way I can build a fully functional & highly effective routing system based on that & later on will implement it on your router file.

**Comment by panique** [comment]
HeHey, I'm currently  "cleaning" the project a little bit and moving feature-requests like this to an own list inside the readme file (find it under the "future features" point). I hope you are okay with it, as  most tickets here are new features and not really bugs or so.

My idea is just to avoid this project from getting oversized by too many features, so I'm closing the ticket, but for sure linking it from the readme in case somebody wants to implement this.

I hope you are all okay with this. :)
