### ISSUE TITLE
mail.sendphpmail always returns true

### ISSUE THREAD

**Issue by 1010101110** [panique/huge#729]
application/core/Mail.php

line: 87 and 89

description: for some reason we aren't saving return code from the mail send function, this means it always returns true (even when send mail fails). current code checks if mail object is still alive for some reason? php mailer returns true / false we should use that!

proposed fix1 or 2: 
![fix](http://i.imgur.com/pcx90WR.png)

oh or move the call into the if(), so we get return value, eitherway

**Comment by panique** [comment]
Good point! Fix coming up!

**Comment by panique** [comment]
Thanks, it's now fixed in develop and master branch!
