### ISSUE TITLE
Support for U2F

### ISSUE THREAD

**Issue by tysonlist** [panique/huge#731]
With GitHub now supporting U2F (https://developers.yubico.com/U2F/), I wonder if it would be worthwhile to optionally implement that into this framework? I'd be willing to help if you think it makes sense.

**Comment by panique** [comment]
Hey, this might be a good idea for a fork or another project! For the current version I think it's a little bit overkill, and most people will definitly not even use it.

Let's put this link and the idea itself into a "possible ideas / features" list into the readme, maybe this encourages people to work on this feature.
