### ISSUE TITLE
Backend-Frontend

### ISSUE THREAD

**Issue by zilinski** [panique/huge#734]
Hi! At first thank you for great framework. I have a question: is it possible to create backend and frontend folders in the framework to separate backend from frontend?

Thanks!

**Comment by panique** [comment]
Hey, thanks! For sure that's possible if you build this on your own, but out of the box it will not work like that, as you'd have to seperate your employyees (which probably use the /backend) and your customers / users (which will use the /frontend part).

But I can strongly recommend using the YII2 frameworks which has exactly that working out of the box, have a look on this official starter barebone here please:
https://github.com/yiisoft/yii2-app-advanced
