### ISSUE TITLE
Need instructions to add template files from vendor dir

### ISSUE THREAD

**Issue by bestamit** [panique/huge#737]
hi , i have added a template through composer and need to include some static files in header/footer.php
how should i do it?
Template : AdminLTE

**Comment by panique** [comment]
I have absolutly no idea what you want

**Comment by bestamit** [comment]
sorry for that.
well here you have implemented super simple MVC framework.
Is there a similar feature like Yii to include assets.

for example : i have installed Web template from composer .
i want to include some template files in View.
is there any ready implementation integrated into it?
