### ISSUE TITLE
Email Activation Link | ahref string with "click here" instead of string?

### ISSUE THREAD

**Issue by sidopufn** [panique/huge#738]
Does anyone have a creative idea on how to make the activation link a simple ahref'd link that says "Click Here to Activate", instead of the long string that is now in the body of the email? This would look much more "professional" and clean.

**Comment by Dominic28** [comment]
You need to set html as content-type.
Take a look at example #4 http://php.net/manual/en/function.mail.php

**Comment by sidopufn** [comment]
I figured this out:

(1) in the class.phpmailer.php file, change "public $ContentType" to 'text/html'

(2) RegistrationModel.php, in public static function sendVerificationEmail add opening " . '<a href="' " and closing " . '">YOUR_ACTIVATION_TEXT</a>" before the "Config::get('URL')" and after the "urlencode($user_activation_hash)"

This should probably be incorporated into a "to do" in the next iteration of the code with a $variable for the YOUR_ACTIVATION_TEXT.

**Comment by panique** [comment]
Thanks, I've linked this from the readme file as "HTML mails" under "community-provided features". Please note that this project should be as simple and minimal as possible dealing with html mails inside a script that's mainly about PHP security is too much.

I'll close this ticket, I hope it's okay for you :)
