### ISSUE TITLE
[QUESTION] Possible to use/create sub method?

### ISSUE THREAD

**Issue by mrgreen222** [panique/huge#743]
Hi and thanks for awesome framework!

Im just wondering how you guys would solve a problem similar to this.

This is my case: I want to create a "sub" forum or what you want to call it, like `http://localhost/huge/public/sub/random/`. Viewing this URL would fetch all posts under sub forum random. But then i want view a the post and all comment, `http://localhost/huge/public/sub/random/post/1`.

Currently i it looks like this in controller:

```
    /**
     * This method controls what happens when you move to /hub/random in your app.
     */
    public function random($post_id = null)
    {
        if($post_id == null){
        // Just for test, here we would fetch all posts
        $this->View->render('hub/random', array('index' => 'random'));
        }elseif($post_id){
                
            // se if there is a post with that ID in databse
            $database = DatabaseFactory::getFactory()->getConnection();
            $sql = "SELECT id, sub_forum FROM posts WHERE id = :post_id and sub_forum = random";
            $query = $database->prepare($sql);
            $query->execute(array(':post_id' => $post_id));
            
            // if not, return negative feedback and redirect to start for random
            if($query->rowCount() == 0){
            Session::add('feedback_negative', 'No post with that ID');
            Redirect::to('hub/random');
            }
        
        }else{
        $this->View->render('hub/post', array('posts' => PostModel::getAllComment($post_id)));
        }
    }
```

The positive part is that I can use hub/post for multipel sub forums. But there is probably another, better way to do this I presume.

**edit**
I need a method for `hub/post` (should be `hub/random/post` but i missed that) as well did i notice. And thats seems like there will be much coding around a problem. Don't really know what to do next =)

**Comment by panique** [comment]
Hi, thanks! Sorry but I don't know how to do this, and I think rewriting the framework is not the best solution here, maybe setting your apache/nginx folder would be better (so all traffic going into forum.yourdomain.com goes to yourdomain.com/huge/public ...

If you really need submethods then you could have a look at Laravel or Symfony, i think they have this feature :)

**Comment by mrgreen222** [comment]
I found (i think) what i was looking for in laravel, http://laravel.com/docs/5.1/routing#route-parameters
```
Route::get('posts/{post}/comments/{comment}', function ($postId, $commentId) {
    //
});
```
To bad that laravel seems so complex, and to bad that huge docent support this type of routing ;)
