### ISSUE TITLE
[TO CLARIFY] session cookie time issue

### ISSUE THREAD

**Issue by gujiman** [panique/huge#744]
when i login (without remeber me) then close the browser the session doesn't get destroyed. hence when i open the browser it will automatically login for me. I think the issue is in:

https://github.com/panique/huge/blob/master/application/model/LoginModel.php

where the session cookies time should be 0 by default??:

        setcookie(session_name(), session_id(), time() + Config::get('SESSION_RUNTIME'),....

should be:

        setcookie(session_name(), session_id(), Config::get('SESSION_RUNTIME'),....

and SESSION_RUNTIME = 0

**Comment by OmarElGabry** [comment]
That's true, the session won't get destroyed because it's [scheduled for 1 week](https://github.com/panique/huge/blob/master/application/config/config.development.php#L101). When assigned to 0, this will keep the session alive until the browser closed.

Some issues have been raised in browsers that don't clear session cookie when the browser is closed, That's why it's better to explicitly set session expiry.

**Comment by gujiman** [comment]
Would setting SESSION_RUNTIME to zero (as default) in the config file be better than the current setting of 1 week?

**Comment by panique** [comment]
Good question! I'm very unsure here...

**Comment by gujiman** [comment]
i think most big sites delete the session when the browser is closed, just incase the user is logged in from a public computer and he/she assumes that by closing the browser will automatically log him out.
If the user wants to be logged in for longer then the 'keep me logged in' box covers it.

**Comment by geozak** [comment]
these two posts give good information about implementing and forcing session timeout.
http://stackoverflow.com/a/1516338
http://stackoverflow.com/a/1270960

I am not sure that I agree with putting the setcookie for sessionname in the loginmodel. I feel that it would be better put in the Session::Init() where the cookie is fundamentally made. And probably better than setting the cookie manually with setcookie we should use session_start() input parameter to set the setting for the session cookie.

**Comment by panique** [comment]
I've added these two links to the readme (and close this ticket for now). Thanks!
