### ISSUE TITLE
[TODO] Auto logout user after acount deleted or suspended

### ISSUE THREAD

**Issue by slaveek** [panique/huge#750]
Account deletion and suspension is great feature in the project and is working flawless. However I think user should be auto log off and access should forbidden right after admin action (delete or suspend user account). If user don't logout, account is still accessible and user can still use account as regular account. Thus if user never do logout action this feature doesn't work :(

IMHO this function should stop to get the access to user account straight away.

**Comment by mrgreen222** [comment]
UPDATE session_id in table `users` to null

**Comment by JFJanssen** [comment]
Is "UPDATE session_id in table users to null" enough?
Should each user request also check if user_active == 1 and?/or? user_deleted == 0?

**Comment by mrgreen222** [comment]
Have a look how the logout function works, `LoginModel::logout()`.

Maybe execute `self::deleteCookie($user_id)` and `Session::updateSessionId($user_id)` on that particular `$userId` been deleted or suspended?

But maybe the best way is to check it `Auth::checkAuthentication`.

**Comment by panique** [comment]
done in develop branch :)
