### ISSUE TITLE
[QUESTION] EOL and a RESTful feature

### ISSUE THREAD

**Issue by abmmhasan** [panique/huge#757]
I've been expecting a RESTful version next from this script! Highly disappointed when I've read the updated readme. Reason is, your script is a real great inspiration to me! Why?
1. I've learned PDO from this project (before huge in php mvc)
2. I knew class system from C++ but your one was next what taught me the PHP class system
3. The MVC architecture, yes that one; I also took a great example from your script
& then I been waiting for the script to become RestFul so I go further. I hoped to add the fourth point with the term "RESTful".
But alas, I found out, you declared EOL..... Yes I know RESTful but that is in theory and with some scattered script. I wanted to arrange them by learning it from this... But, ........ (I don't know if I should request because it is totally open)

**Comment by panique** [comment]
:) Thanks, good to hear that the script is really useful for some people. Thing is, I really really don't have the time to work in this anymore, HUGE (and the earlier projects leading to this) have killed already so much time of my life, and it's not really healthy to spend too much time with open-source.

If you like, then you can always fork the project and do whatever you want with it, it's under the supercool MIT licence which basically says: "Do what you want, it's legal" :)

Maybe you find some people to rebuild it to restful architecture!? Personally I think there are already very good frameworks in the PHP world that come with this feature, so rebuilding HUGE with this might be work that is not really necessary.

Sorry for this, have a wonderful week
Chris
