### ISSUE TITLE
Session Start

### ISSUE THREAD

**Issue by robertdanbaird** [panique/huge#762]
Hi am still a bit new to PHP, so this may have a simple solution. I am trying to squeeze that login between a Header and a Footer, but am getting an error. The error basically says that the page has already posted data and cant start the session. I am using the 'Advanced' version.

basically (index.php)

Include('Header')
Logon stuff
include('Footer')

1. How can i get around this?
2. Will i have the same issue if i switch to HUGE?

Thank You!!

**Comment by panique** [comment]
He, please post a problem with a totally different script in the forum of that script! The login also does not happen "between" header and footer. The login is main application logic, and after that all views are generated. please not mix backend and frontend this way, it will make your application really really hard to use (and it's broken too).

Just use php-login-advadnced in exactly the way it's made, it's all explained and super-easy to use, absolutly no reason to do things in a completely different way.

If you use huge (and if you use php-login-advanced the right way) you'll not have this problem. Keep it simple! :)
