### ISSUE TITLE
Firewall false positive with huge

### ISSUE THREAD

**Issue by cianz** [panique/huge#769]
Not sure if this is really of any concern, or if there's even any way around it, although I suppose it could cause some hair pulling for certain users who don't check their logs or don't have access to them.

I was receiving a '403' error after login, which turned out to be caused by my web host's firewall blocking the login submit. Here is the exact error:

[Wed Dec 30 14:33:36 2015] [error] [client xxxx] ModSecurity:  [file "/usr/local/cwaf/rules/23_SQL_SQLi.conf"] [line "18"] [id "211540"] [rev "2"] [msg "COMODO WAF: Blind SQL Injection Attack"] [data "Matched Data: user_password found within ARGS_NAMES:user_password: user_password"] [severity "CRITICAL"] Access denied with code 403 (phase 2). Pattern match "(?i:\\\\b(?:t(?:able_name\\\\b|extpos[^a-zA-Z0-9_]{1,}\\\\()|(?:a(?:ll_objects|tt(?:rel|typ)id)|column_(?:id|name)|mb_users|object_(?:id|(?:nam|typ)e)|pg_(?:attribute|class)|rownum|s(?:ubstr(?:ing){0,1}|ys(?:c(?:at|o(?:lumn|nstraint)s)|dba|ibm|(?:filegroup|o ..." at ARGS_NAMES:user_password. [hostname "xxxx"] [uri "/xxxx/login/login"] [unique_id "xxxx"]

**Comment by cianz** [comment]
Fixed it by changing 'user_password' to 'user_pw'.

**Comment by panique** [comment]
Oh, interesting case! Personally, it looks like a badly configured firewall to me. Or is it bad style to use "password" inside SQL column names ? I'm totally unsure... This project btw uses "user_password_hash", not "user_password" directly. Do you have more information about the firewall itself, maybe it's a common problem with a nice official workaround.

Can somebody confirm similar issues ?
