### ISSUE TITLE
[fixed in develop branch] Login redirect fail if HUGE dir != root

### ISSUE THREAD

**Issue by ghost** [panique/huge#770]
Hi,

I'm trying first time HUGE script. It seems work good but there's only one problem if you place the system in a sub-directory.

I've put it into http://127.0.0.1/HUGE/

If I try to open protected page like dashboard it redirect us to:
http://127.0.0.1/HUGE/login?redirect=%2FHUGE%2Fdashboard%2F

So, when we login, it redirect to:
http://127.0.0.1/HUGE/HUGE/dashboard/index
-> 404 error

If in LoginController.php change (line 28):
            $data = array('redirect' => Request::get('redirect') ? Request::get('redirect') : NULL);
To:
            $data = array('redirect' => Request::get('redirect') ? "../".Request::get('redirect') : NULL);

With this we avoid 404 page, it redirect now to: http://127.0.0.1//HUGE/dashboard/
And page load, but we have double / after domain.

You have some better solution for that? Can be better to define config file the main root of the script?

Thanks.

**Comment by panique** [comment]
pleae install the project exactly like described in the install tutorial, and please dont put the project in a subfolder, and if you REALLY need to do this then please follow the instructions given in the readme and the config file!!! It's impossible to make this project work out of the box in every possible installation scenario.

**Comment by geozak** [comment]
This is the same as issue #754

**Comment by Vizzielli** [comment]
Ok, I read yesterday files recommended. I reported the problem to see if it could be resolved or if it is expected to be installed in subfolders.

Clearly it is not expected, however if I find an effective solution I'll post it here.

Thank you.

**Comment by slaveek** [comment]
Edit Redirect.php
```php
    public static function to($path)
    {
        header("location: " . Config::get('URL') . $path);
    }
```
to this
```php
    public static function to($path)
    {
        header('location: http://' . $_SERVER['HTTP_HOST'] . '/' . $path);
    }
```

In couple very quick tests redirection works in:

- ROOT dir
- subfolder
- and even if huge is in 2 subfolders as:
```
http://127.0.0.1/subfolder/huge/
```
(the same issue #754)

**Comment by slaveek** [comment]
Sorry!
Redirection to previous viewd page after login works properly but this broke others
This should be as new method like:
``` php
    public static function toPreviousViewdPageAfterLogin($path) 
    {
        header('location: http://' . $_SERVER['HTTP_HOST'] . '/' . $path);
    }
```
and then in LoginController->login()

```php
Redirect::toPreviousViewdPageAfterLogin(ltrim(urldecode(Request::post('redirect')), '/'));
```
sorry again

**Comment by slaveek** [comment]
I tested little bit more solution above and looks it works fine.
But there is one think that @OmarElGabry point in his comment here -> https://github.com/panique/huge/issues/754#issue-119307471

>Another thing, If you entered wrong email/password, the redirect query parameter in URL will be cleared as implemented in LoginController

He's right ;) All parameters are gone.

So final solution included issue pointed by @OmarElGabry can looks:

Add new method to Redirect.php
```php
    public static function toPreviousViewedPageAfterLogin($path) 
    {
        header('location: http://' . $_SERVER['HTTP_HOST'] . '/' . $path);
    }
```

then in LoginController->login() method change this lines:

```php
if ($login_successful) {
    if (Request::post('redirect')) {
        Redirect::to(ltrim(urldecode(Request::post('redirect')), '/'));
    } else {
        Redirect::to('user/index');
    }
} else {
    Redirect::to('login/index');
}
```
to this:
```php
if ($login_successful) {
    if (Request::post('redirect')) {
        Redirect::toPreviousViewedPageAfterLogin(ltrim(urldecode(Request::post('redirect')), '/'));
    } else {
        Redirect::to('user/index');
    }
} else {
    if (Request::post('redirect')) {
        Redirect::to('login?redirect=' . ltrim(urlencode(Request::post('redirect')), '/'));
    } else {
        Redirect::to('login/index');
    }
}
```
BTW I don't like this: toPreviousViewedPageAfterLogin

**Comment by abmmhasan** [comment]
Just updated the Pull #773

**Comment by Vizzielli** [comment]
Sessions nay be the solution? If we set the redirect link as session value with expiration time 1800sec, and we delete it only after successful login? Thi can be usefull also to avoid unfriendly query in the url..

**Comment by abmmhasan** [comment]
I don't support session based redirection! Just rethink! For suppose I was in a link. Now when I login I'll simply cut off that link & login so it will take me normal admin page only. But if it is session based whatever I do, will redirect me to same url again.

**Comment by Vizzielli** [comment]
I supposed that if you join the website with a specific url, probably you want see that specific content. In any case should be an easy modification, so isn't important to find it in the official package. At the end we must only edit redirect+get with redirect+ add session and change login  check for get value with the session value.

**Comment by michael01angelo** [comment]
This may be too late but you can change your Config URL ROOT instead
'URL_ROOT' => 'http://127.0.0.1/subfolder/huge/',
