### ISSUE TITLE
[security] Scrutinizer security issue

### ISSUE THREAD

**Issue by slaveek** [panique/huge#771]
When you go to Scrutinizer

[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/panique/huge/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/panique/huge/?branch=master)

look at the right side "Latest Alerts" section.
There are two new critical issue.

Have you any idea what's that?

The white bug on red icons background right there looks very seriously ;)
I don't know Scrutinizer at all :( so maybe somebody can look at this

**Comment by panique** [comment]
:) no problem, this is just a warning as HUGE has now own namespace:

![bug](https://cloud.githubusercontent.com/assets/156321/12106489/78fe23a6-b360-11e5-8acf-e30e6e226eeb.PNG)
