### ISSUE TITLE
Rename index/index to home/index?

### ISSUE THREAD

**Issue by ChristianGrieger** [panique/huge#779]
Hey guys,

i just got it managed to install huge on my digitalocean server and now try to understand the system.
I stock on the controller right now.

Can someone tell me how to rename that index/index?

I tried to change the application/controller/IndexController.php, the header.php like this:

-...<?php if (View::checkForActiveController($filename, "home")) { echo ' class="active" '; } ...
  .... href="<?php echo Config::get('URL'); ?>home/index">Index.....
 ....-

and renamed the application/view/index folder to application/view/home.

I still get an error 404 :(. So it would be nice if someone can explain me how to use it right?

Thank you very much!

**Comment by ChristianGrieger** [comment]
I did another test with add "test" folder with "index.php" in it and got it working well to access it with "test/index". 
Also another test with a "test" folder and a "test.php" in it works well and is accessible over "test/test", so i understand how to change the controller in both ways to get it working.

But i am still not able to do that with the main index/index folder :(

**Comment by panique** [comment]
hi, please change the default controller from "index" to "home" here: inside https://github.com/panique/huge/blob/4c749c09708cfafb11888ff7bc293a75110b37b7/application/config/config.development.php#L52

**Comment by ChristianGrieger** [comment]
Hey panique, thank you very much! I just got it sorted to create a new folder and set that on config! I really like the system and try to understand it more and more. I am not a good coder but this is a really nice system :)

**Comment by panique** [comment]
Thanks! Cool you've got it working! Have fun & success with the framework :)
