### ISSUE TITLE
[TODO FIX] CaptchaModel::checkCaptcha() to prevent captcha bypass

### ISSUE THREAD

**Issue by elbenjaz** [panique/huge#781]
Hi,

.........................
First of all, congratulations to all for the good job done here!
I've learned a lot (I've followed the project since years ago... php-login-\* times) reading the code/issues/fixes/suggestions/new features... thanks to you who selflessly contribute to the project.
.........................

I've found a little bug. If the session expires is possible to bypass captcha  (if it's not sent)...

CaptchaModel

```
public static function checkCaptcha($captcha) 
{
    if ($captcha == Session::get('captcha')) {
        return true;
    }

    return false;
}
```

... because null == null

I propose this fix (similar like Csrf::isTokenValid() does):

```
public static function checkCaptcha($captcha)
{
    if (Session::get('captcha') && ($captcha == Session::get('captcha'))) {
        return true;
    }

    return false;
}
```

Another question, ¿What GIT client for Linux do you use?

Again, Thanks to all!

**Comment by panique** [comment]
:) Thanks, and excellent eye for the detail, very interesting attacking scenario! Never thought of that to be honest.

**Comment by JFJanssen** [comment]
Wow, well spotted!

**Comment by panique** [comment]
Thanks guys, this is now fixed an merged, a big thanks to @sr-verde for fixing!
