### ISSUE TITLE
General Styling

### ISSUE THREAD

**Issue by rishijavia** [panique/huge#783]
Hi all,

Thank you panique and other contributors for putting together all the efforts into this amazing piece of open source! 

I have been trying to use this script for a personal website and being a fairly new developer I am not able to get me head around how the styling of the script works.

I have been trying to add custom style sheets to pages and its not working at all. I tried adding a style sheet in the same folder as /application/view/_template to edit the header styling but its not recognizing the style sheet at all in the header.php file. How should I go around styling header and contents of pages?

Thank you again for this amazing script. It helps a lot for new developers like me to understand certain concepts and even in development.

**Comment by panique** [comment]
? how about using the .css file for styling ? I mean, seriously...

**Comment by rishijavia** [comment]
lol no, the question not intended on how about using the .css file for styling.

It's about how to use beautiful URL used in the script to point to those files.

Never mind found my answer here:
https://github.com/panique/huge/blob/master/application/config/config.development.php#L42

**Comment by panique** [comment]
Ah okay Sorry ! But it still dont know what you mean.

**Comment by rishijavia** [comment]
I'm sorry for being vague. 
I made a .css file in _template folder and was trying to attach like this:
<link rel="stylesheet" href="style.css" />

But realized I have to attach it like this:
<link rel="stylesheet" href="Config::get('PATH_VIEW').'_templates/style.css'" />

Thanks for your time and the script again :)

**Comment by nitnelav1101** [comment]
Why do you wanna do that? It makes no sense for me.
Also, .css files are stored in root/public/css folder!

**Comment by rishijavia** [comment]
I really don't know why am I doing this but that's how my boss wants it to be, all the styling should go in their particular view folders.

**Comment by panique** [comment]
Okay but thats definitly not a bug or so inside this project, so I'm closing this issue, hope that's okay...
