### ISSUE TITLE
Twig

### ISSUE THREAD

**Issue by mynumbercrunching** [panique/huge#785]

**Comment by mynumbercrunching** [comment]
I finally figured out how to add Twig to Huge if anyone is interested - I am happy to share.
It is amazing how clean and simple the file structure now is. Even adds more speed.
All Views become as simple as this: Twig::render( 'account/index' , $data );
Anyone not aware of Twig:  http://twig.sensiolabs.org/

Thanks to the panique people for their wonderful work!!!

cheers.

**Comment by mrgreen222** [comment]
Can you please explain the benefits with Twig =)

**Comment by mynumbercrunching** [comment]
It is a front-end templating engine such as Smarty or Mustache.

it is much easier then setting up headers and footers for each page via php includes or with the $this-> view.  

I only have  5 templates files in my layouts folder they handle everything.

You create a base template and just extend it on your individual page.  You can add css or jQuery direct to each page without using a special header or footer.

It makes for much cleaner and powerful file structure.  it is even supposed to load faster?

also allows shorthand code which is really nice.

Instead of <?PHP echo $data[‘dog’]->name ?>  you just do {{ dog.name }}.

more on their website or there are some nice videos on youTube.

http://twig.sensiolabs.org

Huge and Twig have made a very awesome site.

good luck and enjoy.

cheers.




> On Jan 19, 2016, at 6:28 PM, mrgreen222 <notifications@github.com> wrote:
> 
> Can you please explain the benefits with Twig =)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/panique/huge/issues/785#issuecomment-172822903>.
> 


thomas wm. benson | student of humanity & citizen of the world  | diogenes@me.com  |  +1. 239 . 206 . 3240  

"The truth is not for all men, but only for those who seek it."  Any Rand

**Comment by mrgreen222** [comment]
Show it in a fork! I would like to see it

**Comment by mynumbercrunching** [comment]
always happy to help...

https://github.com/mynumbercrunching/Huge-and-Twig <https://github.com/mynumbercrunching/Huge-and-Twig>

good luck to all.

**Comment by mouggey** [comment]
Good stuff. Thanks for sharing!

**Comment by hishamazad** [comment]
Uncaught Error: Class 'Twig_Autoloader' , the Twig is not loading

**Comment by hishamazad** [comment]
i found , just remove Twig_Autoloader::register(); where ever you find, it actually auto loads on composer

**Comment by hishamazad** [comment]
i found , just remove Twig_Autoloader::register(); where ever you find, it actually auto loads on composer
also in Controller.php you no need to comment $this->View = new View(); if you have existing views. we can have both twig interface and non twig interface
