### ISSUE TITLE
How to redirect?

### ISSUE THREAD

**Issue by ArneAnka** [panique/huge#786]
I have a `register here. Or sign in here.` on a comment page.

So if i click sign in and enter my credentials, I'm being redirected to `index/index`.

How do i redirect back to the comment page?

**Comment by panique** [comment]
Sorry, I have absoluty no idea what you want to say, and there's also no comment page.

But you can redirect with `Redirect::to('xxxx');` everywhere in the controller, have a look at the redirect-class for more information.

**Comment by ArneAnka** [comment]
Sorry for poor information in my first post =)

I have `comments/view/*` where comments can be viewed on specific topic. And if user is not logged in, they are presented with a option to either sign-in or register.
![skarmavbild 2016-01-31 kl 15 21 18](https://cloud.githubusercontent.com/assets/5988810/12702606/6a7063f2-c82e-11e5-9080-11c26bd0dbf9.png)

And if they click on register or log in, then they will be sent to `login/index/`. And if they sign in, they are being redirected to `index/index/`.

I can't figure out to user [tysonlist´s redirect ](https://github.com/panique/huge/blob/master/application/view/login/index.php) to send them back to `comments/view/*`

Thanks for your time!

**Comment by slaveek** [comment]
Add this to your "login here" link
```php
?redirect=/comments/view/
```
Perfectly will be if  you urlencode this: ```/comments/view/```
