### ISSUE TITLE
[SETUP] Folder structure break IIS web.config

### ISSUE THREAD

**Issue by razuro** [panique/huge#788]
Hi,

Although I believe this is not supported in IIS, I have manage to use version 2.1.1 in IIS using a custom web.config file (.htaccess for IIS). However, the folder structure in version 3 onwards break the web.config.

The main page will load OK, but other page will only point to public. For example, a contact page will have URL like this: http://localhost/huge/public/contact/index

Appreciate anyone that's able to use version 3 with IIS to point me to the right direction.

Thank you very much.

**Comment by razuro** [comment]
I've found the correct web.config. Only one is needed in the root folder. Don't put any web.config in your public folder.

**IIS web.config**
```
<?xml version="1.0" encoding="UTF-8"?><configuration>
    <system.webServer>
        <rewrite>
            <rules>
			
                <rule name="Imported Rule 1" stopProcessing="true">
                    <match url="^(.*)$" ignoreCase="false" />
					<conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="public/index.php?url={R:1}" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

Hello @panique, is it possible to put this as reference for those using IIS? Thank you very much!

**Comment by razuro** [comment]
https://gist.github.com/razuro/38cf2a12db0a86cc3b8e#file-web-config

**Comment by panique** [comment]
Hi, sure, I'll add it in the next days ! Thanks for the nice config :)

**Comment by panique** [comment]
Big thanks, it's now merged and visible in the readme (it will take some minutes until it's visible on github)
