### ISSUE TITLE
[SECURITY][SOLUTION] XXSFilter() with Arrays and Objects

### ISSUE THREAD

**Issue by videsignz** [panique/huge#790]
**UPDATED • Solution** (see below for my original posts)

After looking into the idea of a recursive function suggested by @elbenjaz I have come up with a working solution. Turns out, you need to check `is_array()` and `is_object()`, not just `is_array()`.

``` php
    public static function XSSFilter(&$value)
    {
        if (is_string($value)) {

            $value = htmlspecialchars($value, ENT_QUOTES, 'UTF-8');

        }elseif(is_array($value) || is_object($value)) {

            foreach ($value as $key => &$array_value) {

                self::XSSFilter($array_value);

            }

        }

        return $value;
    }
```

Now, you can run any object, array, or a string value through the `Filter::XSSFilter();`
This works particularly well in the Models where you are fetching data from the database. This keeps your HTML and PHP clean on the views and puts the work in on the Model.

**Single Row Example:**

``` php
    // If successful, clean & return data
    if ($query->rowCount() == 1) {
        $query = $query->fetch();
        return Filter::XSSFilter($query);
    }
```

**Multiple Row Example:**

``` php
    // If successful, clean & return data as array
    if ($query->rowCount() > 0) {
        $query = $query->fetchAll();
        return Filter::XSSFilter($query);
    }
```

**Original Post**

As I was developing today, I was using a custom address model that went something like this which returns an array of key/value pairs....

``` php
$addresses =  AddressModel::getAddresses('user');
```

And in the loop that displays the different address parts I would use the xss filter for each part..

``` php
<?= Filter::XSSFilter($address->$address_line_1) ?>
```

I couldn't help but think, can we create a function for these situations where you need to filter the whole array of values? I tried my hand at it and could not get it to work correctly. The idea is to have both

``` php
Filter::XSSFilter();
Filter::XSSFilterArray();
```

I look forward to your thoughts.
James

**Comment by elbenjaz** [comment]
Hi,

class Filter
{
    public static function XSSFilter(&$value)
    {
        if (is_string($value)) {
            $value = htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
        } else if() {
}

        return $value;
    }
}

**Comment by elbenjaz** [comment]
Hi,

Maybe it should be a recursive method like this (it's just an idea):

class Filter
{
    public static function XSSFilter(&$value)
    {
        if (is_string($value)) {
            $value = htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
        } else if(is_array($value)) {
                foreach ($value as $key=>$item) {
                    $value[$key] = self::XSSFilter(&$value[$key]);
                }
        }

        return $value;
    }
}

**Comment by videsignz** [comment]
@elbenjaz I like the recursive concept, but it doesn't work as is...bummer

**Comment by videsignz** [comment]
So I was able to create the function I was looking for. I like the recursive idea that @elbenjaz suggested but no matter what I do when combining the following two functions, it just breaks.

```php
    public static function XSSFilter(&$value)
    {
        if (is_string($value)) {
            $value = htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
        }

        return $value;
    }
	
    public static function XSSFilterArray(&$array)
    {
		foreach ($array as $key => &$value) {
			self::XSSFilter($value);
		}

        return $array;
    }
```

It's strange because any comparison using

```php
if(is_array($array)){}
```

...seems to get overlooked, even if it IS an array. I am not sure if it has something to do with using a reference to the array instead of a copy. Any ideas how to keep this simple yet combined?

**Comment by panique** [comment]
It's done and merged !
