### ISSUE TITLE
Unable to Navigate other pages from IndexController

### ISSUE THREAD

**Issue by hpng6** [panique/huge#791]
we are using apache 2.4.18, PHP 5.5.32, UBUNTU 14.04.

The default IndexController working properly, but all other pages showing like 

The requested URL /profile/index was not found on this server.
The requested URL /login/index was not found on this server.

**Comment by videsignz** [comment]
If the page does not exist, a custom 404 should be loading, not a server response. Something doesn't seem right.

**Comment by hpng6** [comment]
Tanx for quick reply... we did mistake in VirtualHost.
