### ISSUE TITLE
Duplicated PHPSESSID

### ISSUE THREAD

**Issue by vizzielli** [panique/huge#800]
Why HUGE duplicates the PHPSESSID?

With any configuration domain (prefix dot or not), it creates PHPSESSID in
website.com

And on login it make another PHPSESSID, so with the same name and value, in
.website.com

It's supposed to work like this or may be a problem?

Thank you!

**Comment by panique** [comment]
Well, even after reading your post four times I still have absolutly no idea what you want to say. Please take your time and write a ticket including all necessary information if you want help. You can look into  huge/application/core/Session.php to get an idea how the app handles the session, it's extremely simple, clean and native.

**Comment by vizzielli** [comment]
Sorry, corrector change some words here. Anyway, I've found explaination in LoginModel.php comment ("set session cookie setting manually").

My mistake, sorry again.

**Comment by panique** [comment]
No prob :)
