### ISSUE TITLE
[TEST] some tests are weird :)

### ISSUE THREAD

**Issue by panique** [panique/huge#807]
Some of the tests I've written here are really weird, just saw this when investigating something. Maybe I should never write unit tests with a bottle of red wine open.

This line should return the environment, not the default action
https://github.com/panique/huge/blob/master/tests/core/ConfigTest.php#L30

These lines are not really tests :)
https://github.com/panique/huge/blob/master/tests/core/FilterTest.php#L19

**Comment by videsignz** [comment]
Haha, dude, don't underestimate the productivity power of red wine!

**Comment by panique** [comment]
fixed in upcoming commits
