### ISSUE TITLE
[SPECIAL] remove my gravatar-avatar from github ;) / replace with project icon

### ISSUE THREAD

**Issue by panique** [panique/huge#81]
Unfortunatly, github shows autor's avatars (using the email you provided on github's registration, syncing them with the email you provided on gravatar.com) on projects and don't provide favicons or icons for the projects. It would be nice to find a solution on how to display a project icon here.

**Comment by 4ur3l13n** [comment]
no way to remove my avatar on github?

**Comment by aureIien** [comment]
bah I make the pork ... create a new account get the pick and delete the account 8-P github!
