### ISSUE TITLE
Edge Caching Errors

### ISSUE THREAD

**Issue by zacawee** [panique/huge#812]
When signing in using Microsoft edge if the "remember me for 2 weeks" is not selected you have to re-login on every page.
If you select "Remember me for 2 weeks" then there is a Redirect error and you get stuck on the page "DashboardController/index" and it says "You were successfully logged in via the remember-me-cookie.".
You can then not click on anything else as you are continuously brought back here.
This happens on Edge but not on Chrome.

**Comment by panique** [comment]
Hi, where exactly does this happen ? I mean on your installation or on the live demo ?

**Comment by zacawee** [comment]
On my installation here: 178.62.69.127

**Comment by panique** [comment]
If it works fine in the live demo but not on your installation then it's probably a broken config on your side (pls check the URL used in the cookies, maybe you missed the . in front of url and some browsers automatically fix this, some not)...
