### ISSUE TITLE
Windows?!?!

### ISSUE THREAD

**Issue by zippy4blue** [panique/huge#818]
Hello, love this project, Im just wondering if you have a version that is windows compatible for like xampp? or for editing. Thanks.

**Comment by panique** [comment]
No sorry, this would make things much more complicated, but as most developers use linux boxes inside windows/linux/mac these days it's also not really necessary! The problems you'll have when building something with xampp (and then later deploying on linux) are much bigger than setting up a linux box!

I can really recommend starting with vagrant boxes, it makes things so much better :)

**Comment by geozak** [comment]
I don't understand the request. HUGE works in windows I don't know about XAMPP but I use WampServer (http://www.wampserver.com/en/) and phpstorm just fine on windows.

**Comment by wickedazreal** [comment]
I use XAMPP on my developer laptop, this works fine. 
Be aware when you move your code written in Windows OS to a Linux OS, there might be some issues. I´ve missed a small thing like: text::get() on windows did not work on linux. Should be Text::get().
Case sensitive! =)
