### ISSUE TITLE
Force SSL

### ISSUE THREAD

**Issue by CDServices** [panique/huge#822]
Is there anyway to easily force SSL on the project?]

thanks

**Comment by panique** [comment]
Sure, it should work perfectly when you simply replace http by https in this line:
https://github.com/panique/huge/blob/master/application/config/config.development.php#L36

:)

**Comment by CDServices** [comment]
thank you!

**Comment by ikwijaya** [comment]
Just change http:// to https:// ?
Why i cant use https after change it 
Please advise

**Comment by sr-verde** [comment]
Maybe you want to tell us what is exactly your problem? We don't want to guess.

**Comment by ikwijaya** [comment]
in my case, if i change https://github.com/panique/huge/blob/master/application/config/config.development.php#L36
'URL' => 'http://'
to 
'URL' => 'https://'

i cant access my website. 
so how to solve my problem.

Sorry for my bad english

**Comment by sr-verde** [comment]
Your English is no problem. But what does that mean: „i cant access my website“

**Comment by ikwijaya** [comment]
![2017-03-23_17-16-12](https://cloud.githubusercontent.com/assets/23114902/24243128/8ae8a70a-0fec-11e7-9f18-99e55294b78c.png)

thats it.., i cant reach my web.

**Comment by sr-verde** [comment]
Does your server support TLS-encryption? Does any other website (on your webspace/server) run with HTTPS? Please check that first, it does not seem to be a problem of HUGE.

**Comment by ikwijaya** [comment]
Where i find TLS-Encryption configuration?

**Comment by sr-verde** [comment]
Like I said before: This is not a problem of HUGE. Please contact your hoster for support with your server or webspace.
