### ISSUE TITLE
Running Without Composer!

### ISSUE THREAD

**Issue by abmmhasan** [panique/huge#826]
Well, I'm not a fan of composer! Though, for some, cases it is great too! Anyone who is looking for to run this framework without composer:
Replace the following in public/index.php
`require '../vendor/autoload.php';`
with

```
$classesDir = array (
    '../application/core/',
    '../application/model/'
);
function __autoload($class_name) {
    global $classesDir;
    foreach ($classesDir as $directory) {
        if (file_exists($directory . $class_name . '.php')) {
            require_once ($directory . $class_name . '.php');
            return;
        }
    }
}
```

Though keep one thing in mind, the main framework will run without issue but other plugins that is loaded via composer had to be loaded via require/include/composer. In that case remove these line before running composer.json:

```
 "autoload": {
        "psr-4": { "": ["application/core/", "application/model/"] }
    }
```

**Comment by panique** [comment]
Ok thanks, i'll link this in the readme!
