### ISSUE TITLE
[Question] Uneccesary Production Files

### ISSUE THREAD

**Issue by videsignz** [panique/huge#827]
Hey Everyone,

Is there any documentation on which folders/files can be removed in production. I know there is quite a bit used for testing and such but I feel those files are not suited or needed on a live server.

Can anyone help with this a bit?

**Comment by elbenjaz** [comment]
Hi,

I've removed the folders "/_one-click-installation", "/_pictures", "/tests", "application/_installation".
Also I followed the instructions in the README.md file (section: What the hell are .travis.yml, .scrutinizer.yml etc.) and I deleted all the files except .htaccess, composer.json

**Comment by videsignz** [comment]
@elbenjaz Thanks for the reply...I have done the same regarding those files. I was looking a bit deeper like in the vendor folder...Items such as:

PHPUnit
Symfany
Sebastian
PHPSpec
Doctrine

**Comment by videsignz** [comment]
I'n not completely in tune with what those scripts do and what purpose they have in the app. Therefore, I was hoping for answers here.

**Comment by panique** [comment]
:) Hey, the only files that are needed are:

application/*.*
public/*.*
index.php
composer.json

The rest is just for tests, auto-installation, images for the repo etc...

**Comment by videsignz** [comment]
@panique Hey Chris,

What about gregwar/captcha, phpmailer, and the composer folder? I assume those are necessary?

**Comment by videsignz** [comment]
Wow, I am really not up to date on Composer and the proper ways to use it. ughhhhh....

**Comment by panique** [comment]
:) You'll definitly need the vendor folder in production too, as it holds all the external libraries you (or your framework or both) need, so there's not really a big difference between dev/test/production (except testing etc), please just have a look on all the awesome tutorials on composer, it's really easy to understand and it will make your development so much easier and faster and cleaner :)
