### ISSUE TITLE
Testing the rewrite url in nginx / 1.10.1 is unsuccessful, open the subfolder to download the PHP file

### ISSUE THREAD

**Issue by dnybz** [panique/huge#828]
# vi test.com.conf

server {
    listen       80;
    server_name  *.test.com;

```
#charset koi8-r;

#access_log  logs/host.access.log  main;

location / {
    root   /usr/local/www/nginx/test.com;
    index  index.html index.php;
    #rewrite
    location / {
    try_files $uri /index.php?url=$uri&$args;
    }
}


#error_page  404              /404.html;

# redirect server error pages to the static page /50x.html
#
error_page   500 502 503 504  /50x.html;
location = /50x.html {
    root   /usr/local/www/nginx-dist;
}

# proxy the PHP scripts to Apache listening on 127.0.0.1:80
#
#location ~ \.php$ {
#    proxy_pass   http://127.0.0.1;
#}

# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
#
location ~ \.php$ {
    root           html;
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME /usr/local/www/nginx/test.com$fastcgi_script_name;
    include        fastcgi_params;
}

# deny access to .htaccess files, if Apache's document root
# concurs with nginx's one
#
#location ~ /\.ht {
#    deny  all;
#}
```

}
# /usr/local/sbin/nginx -v

nginx version: nginx/1.10.1

**Comment by dnybz** [comment]
RewriteEngine On

# When using the script within a sub-folder, put this path here, like /mysubfolder/
# If your app is in the root of your web folder, then please delete this line or comment it out
RewriteBase /

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-l

RewriteRule ^(.+)$ index.php?url=$1 [QSA,L]


In apache above test Ok， but nginx is unsuccessful

**Comment by panique** [comment]
Sorry, but I have absolutly no idea what you want to say..

**Comment by dnybz** [comment]
Thank you, has been resolved, the description may be unclear, sorry.

        #rewrite
        if (!-e $request_filename){
                rewrite ^/(.+)$ /index.php?url=$1 last;
        }
