### ISSUE TITLE
Routing!

### ISSUE THREAD

**Issue by abmmhasan** [panique/huge#830]
Are you controlling the Routing using only **core/view.php** file? As I think so! If I'm wrong is there any other files involved on routing? 
I was reviewing (for the first time) the huge 3.0 project!

**Comment by panique** [comment]
Hi there, no sorry the routing is more or less done via the logic in `https://github.com/panique/huge/blob/master/application/core/Application.php`, so when the user hits a URL like ".../user/view/17", then the framework will look if there's a controller called "UserController" with a method "view", call this and pass the parameter "17" to the "view" method.

Most big frameworks have real routing where you can configurate where exactly every URL path should go to, but in this frameworks it's just made in this supersimple way!
