### ISSUE TITLE
Add Better i18n solution

### ISSUE THREAD

**Issue by mirazmac** [panique/huge#843]
Instead of using the old-school array solution. Can we please use **Gettext MO** files. Just like WordPress. As PHP's native gettext is loaded with bugs, there is a very good library created by **PHPMyAdmin**.
https://github.com/phpmyadmin/motranslator
If we use **Gettext MO** files we could easily scan and translate the strings with programs like **POedit**.
Sorry for my bad English. This project is great by the way <3

**Comment by panique** [comment]
Thanks, this is awesome solution, but HUGE is not developed anymore! So you'll have to replace this inside your own project or just fork the project. Sorry!

**Comment by mirazmac** [comment]
Thank you!
Btw, I love your works man! Mini3 and Huge, they are awesome!

**Comment by panique** [comment]
Thanks for the nice words :)
