### ISSUE TITLE
View in subfolder

### ISSUE THREAD

**Issue by raqulka** [panique/huge#845]
I really like this starting template but would like to extend it a little or ask for guidance.

I would like to have a view in subfolder so the structure would look like this:
views
--medicines

----medicine1
----info.php
------forms
--------male.php
--------female.php

----medicine2
----info.php
------forms
--------male.php
--------female.php

----medicine3
----info.php
------forms
--------male.php
--------female.php

Is this something easy to implement or would it require a lot of work?

**Comment by elbenjaz** [comment]
You can do it like this:

```
$this->View->render('medicines/medicine1/info')
$this->View->render('medicines/medicine2/forms/male')
```

Take a look at /application/core/View.php ::render() to see how it works.

**Comment by raqulka** [comment]
Yeah. that part is done and works fine. But how can I get the url to be for example URL/medicines/medicine1/forms/male ? Whereas medicines are controller and medicine one is an action but I would need to have 2 actions then? Because if I render the view like you said, I dont get any errors, but the page will still be URL/medicines/medicine1. 

Any help appreciated!

**Comment by raqulka** [comment]
BUMP!

**Comment by sr-verde** [comment]
I'm not sure if I get your problem: You control the URL with the name and the given variables in the controller. So you can have a function like

`public function medicines($one, $two, $three)`

If `$three` is optional, you can do it like that:

`public function medicines($one, $two, $three = '')`

I'm not sure if that is very pretty, but should work.
