### ISSUE TITLE
Nee help with migration

### ISSUE THREAD

**Issue by myselfgaurav** [panique/huge#856]
Hi i need help in migrating code , i did tried to migrate code to my php 7 server i did below steps

1: my host config file 

```
<Directory "/var/www/html/public">
	AllowOverride All
	Require all granted
</Directory>
```

2: i put all code inside **html** from my old sever to **html** folder of new new server

when  i open url it give me : HTTP ERROR 500

Please help me with urgent issue 

i am missing something

**Comment by panique** [comment]
Sorry i have no idea what you mean! Please install the application exactly like described in the install tutorial or use the auto-installer

**Comment by myselfgaurav** [comment]
solved it was issue with php 7
