### ISSUE TITLE
PHP code analizing does not work.

### ISSUE THREAD

**Issue by mauro-balades** [panique/huge#900]
Some of the links in the readme, don't work (in the code analyzing section).

**Comment by panique** [comment]
Hi mauro, yes, this project has reached its End of Life 5 years ago, so some links might not work anymore, but I think it doesn make sense to "fix" it, as these articles itself do not exist anymore. If you are looking for a PHP framework then I can recommend Laravel or Slim !

**Comment by mauro-balades** [comment]
I understand. But I am a bit sad this project has ended especially with all the potential it has.

**Comment by losttheplot** [comment]
There is nothing stopping you from using this project as the core of something that you learn from and expand as you go. The code is stable and secure and a very good starting point from which to build a massive application that is focussed on exactly what you need it to be.

If you don't have the knowledge or experience to do so, and are unwilling to invest the time needed to add on all the secondary systems needed for your particular needs, then as panique alludes to, there are more PHP frameworks out there than you could possibly count. But large frameworks have bloat coming out of their seams, need constant attention to keep on top of the endless updates and changes, and they force you to use secondary mechanisms that might be far from ideal for you or your skillset. You can end up maintaining your own system, that you only understand on a superficial level, which is a huge liability if your product is mission-critical.

Most people take the frameworks, warts an' all, but it's a free world and I for one used Huge as a starting point, learnt and researched well as I went, adding or building exactly what sub-systems were right for me and the way I think, and I have ended up with a colossal ERP that I am very happy with. Accordingly, I'd like to thank panique very much for publishing this simple but sound project which flies in the face of so much over-complication found in the plethora of one-size-fits-all php frameworks ...thank you :)
